# PANDAS

## Introduction

- Pandas is a Python library used for working with data sets
- The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.
- It has functions for analyzing, cleaning, exploring, and manipulating data.

## Why Use Pandas?

- Pandas allows us to analyze big data and make conclusions based on statistical theories.
- Pandas can clean messy data sets, and make them readable and relevant.
- Relevant data is very important in data science.

## What can Pandas do?

Pandas gives you answers about the data. Like:
- Is there a correlation between two or more columns?
- What is average value?
- Max value?
- Min value?
### Data cleaning:
Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

## Where is the Pandas codebase?
The source code for Pandas is located at this github repository https://github.com/pandas-dev/pandas

# 1)Pandas Series
- A Pandas Series is like a column in a table.
- It is a one-dimensional array holding data of any type.
## Example
Create a simple Pandas Series from a list:

In [10]:
import pandas as pd
a=[1,2,3,4]
sr1= pd.Series(a)
sr1

0    1
1    2
2    3
3    4
dtype: int64

### Labels
- If nothing else is specified, the values are labeled with their index number.
- First value has index 0, second value has index 1 etc.
- This label can be used to access a specified value.
### Example
Return the first value of the Series:

In [12]:
sr1[0]

1

### Create Your Own Labels
- With the index argument, you can name your own labels.
### Example

In [14]:
import pandas as pd
a=[1,2,3,4]
sr2=pd.Series(a, index=["w", "x", "y","z"])
sr2

w    1
x    2
y    3
z    4
dtype: int64

#### Accessing through label

In [16]:
sr2["y"]

3

## Key/value object as Series (Dictionary)
You can also use a key/value object, like a dictionary, when creating a Series.

**Note:** The keys of the dictionary become the labels.
### Example
Create a simple Pandas Series from a dictionary:

In [18]:
import pandas as pd
a={"1st": "Ahmad", "2nd":"Faizan", "3rd":"Fatima"}
positionholders=pd.Series(a)
positionholders

1st     Ahmad
2nd    Faizan
3rd    Fatima
dtype: object

In [19]:
positionholders["1st"]

'Ahmad'

***NOTE:*** To select only some of the items in the dictionary, use the index argument and specify only the items you want to include in the Series.
### Example
Create a Series using only data from "1st" and "2nd":

In [21]:
import pandas as pd
a={"1st":"Ahmad","2nd":"Faizan","3rd":"Fatima"}
pos_hol=pd.Series(a, index=["1st","2nd"])
pos_hol

1st     Ahmad
2nd    Faizan
dtype: object

# 2)Pandas Dataframe
- A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.
- For now consider it like an Excel sheet.
### Example
Create a simple Pandas DataFrame:

In [23]:
import pandas as pd
data={"Name":["Rubaisha", "Malaika", "Ayesha", "Fariha"], "CGPA":[3.55, 3.58, 3.21, 3.22], "City":["BWP","JHL","SWL","SWL"], "Hobby":["Singing","Dancing","Reading","Baking"]}
#load data into dataframe object
df1= pd.DataFrame(data)
df1

       Name  CGPA City    Hobby
0  Rubaisha  3.55  BWP  Singing
1   Malaika  3.58  JHL  Dancing
2    Ayesha  3.21  SWL  Reading
3    Fariha  3.22  SWL   Baking

### Locate Row
- As you can see from the result above, the DataFrame is like a table with rows and columns.
- Pandas use the loc attribute to return one or more specified row(s).
### Example
return row 3: (***Note:*** *This example returns a Pandas Series.*)

In [25]:
df1.loc[3]

Name     Fariha
CGPA       3.22
City        SWL
Hobby    Baking
Name: 3, dtype: object

return row 1 and row 0:

In [27]:
df1.loc[[0,1]] #Note: When using [], the result is a Pandas DataFrame.

       Name  CGPA City    Hobby
0  Rubaisha  3.55  BWP  Singing
1   Malaika  3.58  JHL  Dancing

## Named Indexes
With the index argument, you can name your own indexes.
### Example
Add a list of names to give each row a name:

In [29]:
import pandas as pd
data={"Name":["Rubaisha", "Malaika", "Ayesha", "Fariha"], "CGPA":[3.55, 3.58, 3.21, 3.22], "City":["BWP","JHL","SWL","SWL"], "Hobby":["Singing","Dancing","Reading","Baking"]}
df2=pd.DataFrame(data, index=[236,240,251,243])
df2

         Name  CGPA City    Hobby
236  Rubaisha  3.55  BWP  Singing
240   Malaika  3.58  JHL  Dancing
251    Ayesha  3.21  SWL  Reading
243    Fariha  3.22  SWL   Baking

## Locate Named Indexes
Use the named index in the loc attribute to return the specified row(s).
### Example
**1 -** Return 251:

In [31]:
df2.loc[251]

Name      Ayesha
CGPA        3.21
City         SWL
Hobby    Reading
Name: 251, dtype: object

**2 -** Return 240 and 243:

In [33]:
df2.loc[[240,243]]

        Name  CGPA City    Hobby
240  Malaika  3.58  JHL  Dancing
243   Fariha  3.22  SWL   Baking

# 3)Pandas Read CSV Files
- A simple way to store big data sets is to use CSV files (comma separated values files).
- CSV files contains plain text and is a well know format that can be read by everyone including Pandas.
- In our examples we will be using a CSV file called 'data.csv'.
### Example
Load the CSV into a DataFrame:

***NOTE:*** *If you have a large DataFrame with many rows, Pandas will only return the first 5 rows, and the last 5 rows*

In [35]:
import pandas as pd

##df1=pd.read_csv("data.csv") - will generate error as this file is not located in the same folder i.e. pandas folder so we have to put the directory of file also

df3= pd.read_csv('C:/Users/DELL/Downloads/data.csv')
df3

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

***TIP:*** *to print entire dataframe use to_string() method*

In [37]:
df3= pd.read_csv('C:/Users/DELL/Downloads/data.csv')
df3.to_string()

'     Duration  Pulse  Maxpulse  Calories\n0          60    110       130     409.1\n1          60    117       145     479.0\n2          60    103       135     340.0\n3          45    109       175     282.4\n4          45    117       148     406.0\n5          60    102       127     300.0\n6          60    110       136     374.0\n7          45    104       134     253.3\n8          30    109       133     195.1\n9          60     98       124     269.0\n10         60    103       147     329.3\n11         60    100       120     250.7\n12         60    106       128     345.3\n13         60    104       132     379.3\n14         60     98       123     275.0\n15         60     98       120     215.2\n16         60    100       120     300.0\n17         45     90       112       NaN\n18         60    103       123     323.0\n19         45     97       125     243.0\n20         60    108       131     364.2\n21         45    100       119     282.0\n22         60    130       101     300.0\n23         45    105       132     246.0\n24         60    102       126     334.5\n25         60    100       120     250.0\n26         60     92       118     241.0\n27         60    103       132       NaN\n28         60    100       132     280.0\n29         60    102       129     380.3\n30         60     92       115     243.0\n31         45     90       112     180.1\n32         60    101       124     299.0\n33         60     93       113     223.0\n34         60    107       136     361.0\n35         60    114       140     415.0\n36         60    102       127     300.0\n37         60    100       120     300.0\n38         60    100       120     300.0\n39         45    104       129     266.0\n40         45     90       112     180.1\n41         60     98       126     286.0\n42         60    100       122     329.4\n43         60    111       138     400.0\n44         60    111       131     397.0\n45         60     99       119     273.0\n46         60    109       153     387.6\n47         45    111       136     300.0\n48         45    108       129     298.0\n49         60    111       139     397.6\n50         60    107       136     380.2\n51         80    123       146     643.1\n52         60    106       130     263.0\n53         60    118       151     486.0\n54         30    136       175     238.0\n55         60    121       146     450.7\n56         60    118       121     413.0\n57         45    115       144     305.0\n58         20    153       172     226.4\n59         45    123       152     321.0\n60        210    108       160    1376.0\n61        160    110       137    1034.4\n62        160    109       135     853.0\n63         45    118       141     341.0\n64         20    110       130     131.4\n65        180     90       130     800.4\n66        150    105       135     873.4\n67        150    107       130     816.0\n68         20    106       136     110.4\n69        300    108       143    1500.2\n70        150     97       129    1115.0\n71         60    109       153     387.6\n72         90    100       127     700.0\n73        150     97       127     953.2\n74         45    114       146     304.0\n75         90     98       125     563.2\n76         45    105       134     251.0\n77         45    110       141     300.0\n78        120    100       130     500.4\n79        270    100       131    1729.0\n80         30    159       182     319.2\n81         45    149       169     344.0\n82         30    103       139     151.1\n83        120    100       130     500.0\n84         45    100       120     225.3\n85         30    151       170     300.0\n86         45    102       136     234.0\n87        120    100       157    1000.1\n88         45    129       103     242.0\n89         20     83       107      50.3\n90        180    101       127     600.1\n91         45    107       137       NaN\n92         30     90       107     105.3\n93         15     80       100      50.5\n94         20    150       171     127.4\n95         20    151       168     229.4\n96         30     95       128     128.2\n97         25    152       168     244.2\n98         30    109       131     188.2\n99         90     93       124     604.1\n100        20     95       112      77.7\n101        90     90       110     500.0\n102        90     90       100     500.0\n103        90     90       100     500.4\n104        30     92       108      92.7\n105        30     93       128     124.0\n106       180     90       120     800.3\n107        30     90       120      86.2\n108        90     90       120     500.3\n109       210    137       184    1860.4\n110        60    102       124     325.2\n111        45    107       124     275.0\n112        15    124       139     124.2\n113        45    100       120     225.3\n114        60    108       131     367.6\n115        60    108       151     351.7\n116        60    116       141     443.0\n117        60     97       122     277.4\n118        60    105       125       NaN\n119        60    103       124     332.7\n120        30    112       137     193.9\n121        45    100       120     100.7\n122        60    119       169     336.7\n123        60    107       127     344.9\n124        60    111       151     368.5\n125        60     98       122     271.0\n126        60     97       124     275.3\n127        60    109       127     382.0\n128        90     99       125     466.4\n129        60    114       151     384.0\n130        60    104       134     342.5\n131        60    107       138     357.5\n132        60    103       133     335.0\n133        60    106       132     327.5\n134        60    103       136     339.0\n135        20    136       156     189.0\n136        45    117       143     317.7\n137        45    115       137     318.0\n138        45    113       138     308.0\n139        20    141       162     222.4\n140        60    108       135     390.0\n141        60     97       127       NaN\n142        45    100       120     250.4\n143        45    122       149     335.4\n144        60    136       170     470.2\n145        45    106       126     270.8\n146        60    107       136     400.0\n147        60    112       146     361.9\n148        30    103       127     185.0\n149        60    110       150     409.4\n150        60    106       134     343.0\n151        60    109       129     353.2\n152        60    109       138     374.0\n153        30    150       167     275.8\n154        60    105       128     328.0\n155        60    111       151     368.5\n156        60     97       131     270.4\n157        60    100       120     270.4\n158        60    114       150     382.8\n159        30     80       120     240.9\n160        30     85       120     250.4\n161        45     90       130     260.4\n162        45     95       130     270.0\n163        45    100       140     280.9\n164        60    105       140     290.8\n165        60    110       145     300.0\n166        60    115       145     310.2\n167        75    120       150     320.4\n168        75    125       150     330.4'

### Converting a dataframe into a csv file

In [39]:
df2.to_csv("friends.csv")

### Loading a csv file from the same location as Pandas file

In [41]:
df4= pd.read_csv("friends.csv") #it works here as both friends.csv and pandas are at same location
df4

   Unnamed: 0      Name  CGPA City    Hobby
0         236  Rubaisha  3.55  BWP  Singing
1         240   Malaika  3.58  JHL  Dancing
2         251    Ayesha  3.21  SWL  Reading
3         243    Fariha  3.22  SWL   Baking

***Now if you dont want to show indexes in your excel sheet then you can remove it as:***

In [43]:
df2.to_csv("friends_no_index.csv", index=False)

## Max Rows
- The number of rows returned is defined in Pandas option settings.
- You can check your system's maximum rows with the pd.options.display.max_rows statement.
### Example
**1) Check the number of maximum returned rows:**

In [45]:
import pandas as pd
print(pd.options.display.max_rows)

60

**2)We can also do:**

In [47]:
print(pd.options.display.max_info_rows) #max_info_rows
print(pd.options.display.min_rows) #min_rows
print(pd.options.display.max_columns) #max_columns
print(pd.options.display.max_info_columns) #max_info_columns

1690785
10
20
100

### Changing the max rows number
You can change the maximum rows number with the same statement.
### Example
Increase the maximum number of rows to display the entire DataFrame:

In [49]:
import pandas as pd
pd.options.display.max_rows=9999
df5= pd.read_csv("C:/Users/DELL/Downloads/data.csv")
df5

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

#### we can also view rows using df.head() and df.tail() methods

In [51]:
df5.head(2) #first 2 records

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0

In [52]:
df5.tail(2) #last 2 records

     Duration  Pulse  Maxpulse  Calories
167        75    120       150     320.4
168        75    125       150     330.4

#### inorder to do statistical analysis of mathematical column we cam use df.describe() method

In [54]:
# lets take df1 with CGPA as mathematical column
df1.describe()

           CGPA
count  4.000000
mean   3.390000
std    0.202485
min    3.210000
25%    3.217500
50%    3.385000
75%    3.557500
max    3.580000

### Changing elements
you can change the elements of a record by accessing column as:

In [56]:
data= pd.read_csv("friends.csv")
data

   Unnamed: 0      Name  CGPA City    Hobby
0         236  Rubaisha  3.55  BWP  Singing
1         240   Malaika  3.58  JHL  Dancing
2         251    Ayesha  3.21  SWL  Reading
3         243    Fariha  3.22  SWL   Baking

In [57]:
data["CGPA"] #will return entire CGPA column

0    3.55
1    3.58
2    3.21
3    3.22
Name: CGPA, dtype: float64

#### Example
change the cgpa of Ayesha from 3.21 to 3.25

In [59]:
data["CGPA"][2]=3.25

C:\Users\DELL\AppData\Local\Temp\ipykernel_18544\1524519985.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["CGPA"][2]=3.25

In [60]:
data  #cgpa of ayesha now will be 3.25

   Unnamed: 0      Name  CGPA City    Hobby
0         236  Rubaisha  3.55  BWP  Singing
1         240   Malaika  3.58  JHL  Dancing
2         251    Ayesha  3.25  SWL  Reading
3         243    Fariha  3.22  SWL   Baking

In [61]:
data.to_csv("updated.csv") #new csv with updated cgpa of ayesha

# 4) Pandas Excel Files
we can also access and read excel data same as csv data

In [63]:
import pandas as pd
ex1= pd.read_excel("excelsample.xlsx")
ex1

,First Name,Last Name,Company Name,Address,City,State,Phone No,Email,Web
0,Rebbecca,Didio,"Brandt, Jonathan F Esq",171 E 24th St,Leith,TAS,03-8174-9123,rebbecca.didio@didio.com.au,http://www.brandtjonathanfesq.com.au
1,Stevie,Hallo,Landrum Temporary Services,22222 Acoma St,Proston,QLD,07-9997-3366,stevie.hallo@hotmail.com,http://www.landrumtemporaryservices.com.au
2,Mariko,Stayer,"Inabinet, Macre Esq",534 Schoenborn St #51,Hamel,WA,08-5558-9019,mariko_stayer@hotmail.com,http://www.inabinetmacreesq.com.au
3,Gerardo,Woodka,Morris Downing & Sherred,69206 Jackson Ave,Talmalmo,NSW,02-6044-4682,gerardo_woodka@hotmail.com,http://www.morrisdowningsherred.com.au
4,Mayra,Bena,"Buelt, David L Esq",808 Glen Cove Ave,Lane Cove,NSW,02-1455-6085,mayra.bena@gmail.com,http://www.bueltdavidlesq.com.au
5,Idella,Scotland,Artesian Ice & Cold Storage Co,373 Lafayette St,Cartmeticup,WA,08-7868-1355,idella@hotmail.com,http://www.artesianicecoldstorageco.com.au
6,Sherill,Klar,Midway Hotel,87 Sylvan Ave,Nyamup,WA,08-6522-8931,sklar@hotmail.com,http://www.midwayhotel.com.au
7,Ena,Desjardiws,"Selsor, Robert J Esq",60562 Ky Rt 321,Bendick Murrell,NSW,02-5226-9402,ena_desjardiws@desjardiws.com.au,http://www.selsorrobertjesq.com.au
8,Vince,Siena,Vincent J Petti & Co,70 S 18th Pl,Purrawunda,QLD,07-3184-9989,vince_siena@yahoo.com,http://www.vincentjpettico.com.au
9,Theron,Jarding,"Prentiss, Paul F Esq",8839 Ventura Blvd,Blanchetown,SA,08-6890-4661,tjarding@hotmail.com,http://www.prentisspaulfesq.com.au
10,Amira,Chudej,Public Works Department,3684 N Wacker Dr,Rockside,QLD,07-8135-3271,amira.chudej@chudej.net.au,http://www.publicworksdepartment.com.au
11,Marica,Tarbor,Prudential Lighting Corp,68828 S 32nd St #6,Rosegarland,TAS,03-1174-6817,marica.tarbor@hotmail.com,http://www.prudentiallightingcorp.com.au
12,Shawna,Albrough,"Wood, J Scott Esq",43157 Cypress St,Ringwood,QLD,07-7977-6039,shawna.albrough@albrough.com.au,http://www.woodjscottesq.com.au
13,Paulina,Maker,Swanson Peterson Fnrl Home Inc,6 S Hanover Ave,Maylands,WA,08-8344-8929,paulina_maker@maker.net.au,http://www.swansonpetersonfnrlhomeinc.com.au
14,Rose,Jebb,Old Cider Mill Grove,27916 Tarrytown Rd,Wooloowin,QLD,07-4941-9471,rose@jebb.net.au,http://www.oldcidermillgrove.com.au
15,Reita,Tabar,Cooper Myers Y Co,79620 Timber Dr,Arthurville,NSW,02-3518-7078,rtabar@hotmail.com,http://www.coopermyersyco.com.au
16,Maybelle,Bewley,Angelo International,387 Airway Cir #62,Mapleton,QLD,07-9387-7293,mbewley@yahoo.com,http://www.angelointernational.com.au
17,Camellia,Pylant,"Blackley, William J Pa",570 W Pine St,Tuggerawong,NSW,02-5171-4345,camellia_pylant@gmail.com,http://www.blackleywilliamjpa.com.au
18,Roy,Nybo,Phoenix Phototype,823 Fishers Ln,Red Hill,ACT,02-5311-7778,rnybo@nybo.net.au,http://www.phoenixphototype.com.au
19,Albert,Sonier,Quartzite Processing Inc,4 Brookcrest Dr #7786,Inverlaw,QLD,07-9354-2612,albert.sonier@gmail.com,http://www.quartziteprocessinginc.com.au
20,Hayley,Taghon,Biltmore Textile Co Inc,72 Wyoming Ave,Eugowra,NSW,02-1638-4380,htaghon@taghon.net.au,http://www.biltmoretextilecoinc.com.au
21,Norah,Daleo,Gateway Refrigeration,754 Sammis Ave,Kotara Fair,NSW,02-5322-6127,ndaleo@daleo.net.au,http://www.gatewayrefrigeration.com.au
22,Rosina,Sidhu,Anchorage Yamaha,660 N Green St,Burpengary,QLD,07-6460-4488,rosina_sidhu@gmail.com,http://www.anchorageyamaha.com.au
23,Royal,Costeira,Wynns Precision Inc Az Div,970 Waterloo Rd,Ellis Beach,QLD,07-5338-6357,royal_costeira@costeira.com.au,http://www.wynnsprecisionincazdiv.com.au
24,Barrie,Nicley,Paragon Cable Tv,4129 Abbott Dr,Fish Creek,VIC,03-6443-2786,bnicley@nicley.com.au,http://www.paragoncabletv.com.au
25,Linsey,Gedman,Eagle Computer Services Inc,1529 Prince Rodgers Ave,Kennedy,QLD,07-4785-3781,lgedman@gedman.net.au,http://www.eaglecomputerservicesinc.com.au
26,Laura,Bourbonnais,Kansas Association Ins Agtts,2 N Valley Mills Dr,Cape Portland,TAS,03-6543-6688,laura.bourbonnais@yahoo.com,http://www.kansasassociationinsagtts.com.au
27,Fanny,Stoneking,"Di Giacomo, Richard F Esq",50968 Kurtz St #45,Warra,QLD,07-3721-9123,fstoneking@hotmail.com,http://www.digiacomorichardfesq.com.au
28,Kristian,Ellerbusch,"Butler, Frank B Esq",71585 S Ayon Ave #9,Wanguri,NT,08-2748-1250,kristian@yahoo.com,http://www.butlerfrankbesq.com.au
29,Gwen,Julye,Alphagraphics Printshops,8 Old County Rd #3,Alvie,VIC,03-7063-6734,gjulye@hotmail.com,http://www.alphagraphicsprintshops.com.au
30,Ben,Majorga,Voyager Travel Service,13904 S 35th St,Wherrol Flat,NSW,02-8171-9051,ben.majorga@hotmail.com,http://www.voyagertravelservice.com.au
31,Trina,Oto,N Amer Plast & Chemls Co Inc,6149 Kapiolani Blvd #6,Placid Hills,QLD,07-1153-8567,trina@oto.com.au,http://www.namerplastchemlscoinc.com.au
32,Emelda,Geffers,D L Downing General Contr Inc,95431 34th Ave #62,Nedlands,WA,08-7097-3947,emelda.geffers@gmail.com,http://www.dldowninggeneralcontrinc.com.au
33,Zana,Ploszaj,Community Insurance Agy Inc,25 Swift Ave,Auchenflower,QLD,07-7991-8880,zana_ploszaj@ploszaj.net.au,http://www.communityinsuranceagyinc.com.au
34,Shaun,Rael,House Of Ing,14304 Old Alexandria Ferry Rd,Buninyong,VIC,03-8998-5485,shaun.rael@rael.com.au,http://www.houseofing.com.au
35,Oren,Lobosco,Vei Inc,1585 Salem Church Rd #59,Dangar Island,NSW,02-5046-1307,olobosco@hotmail.com,http://www.veiinc.com.au
36,Catherin,Aguele,"Hanna, Robert J Esq",75962 E Drinker St,Sunny Nook,QLD,07-6476-1399,caguele@gmail.com,http://www.hannarobertjesq.com.au
37,Pearlene,Boudrie,Design Rite Homes Inc,8978 W Henrietta Rd,Minden,QLD,07-4463-7223,pboudrie@boudrie.net.au,http://www.designritehomesinc.com.au
38,Kathryn,Bonalumi,State Library,86 Worth St #272,Tibradden,WA,08-3071-2258,kathryn.bonalumi@yahoo.com,http://www.statelibrary.com.au
39,Suzan,Landa,Vista Grande Baptist Church,15 Campville Rd #191,Clermont,QLD,07-1576-1412,suzan.landa@gmail.com,http://www.vistagrandebaptistchurch.com.au
40,Sommer,Agar,Poole Publications Inc,3 N Ridge Ave,Kadina,SA,08-9130-3372,sagar@agar.net.au,http://www.poolepublicationsinc.com.au
41,Keena,Rebich,Affilated Consulting Group Inc,3713 Poway Rd,Sawtell,NSW,02-4972-3570,krebich@rebich.net.au,http://www.affilatedconsultinggroupinc.com.au
42,Rupert,Hinkson,Northwestern Mutual Life Ins,1 E 17th St,East Gosford,NSW,02-7160-2066,rupert_hinkson@hinkson.net.au,http://www.northwesternmutuallifeins.com.au
43,Aleta,Poarch,Barrett Burke Wilson Castl,5 Liberty Ave,Fosterville,VIC,03-2691-1298,apoarch@gmail.com,http://www.barrettburkewilsoncastl.com.au
44,Jamal,Korczynski,Helricks Inc,404 Broxton Ave,Bateau Bay,NSW,02-3877-9654,jamal_korczynski@gmail.com,http://www.helricksinc.com.au
45,Luz,Broccoli,"Wynn, Mary Ellen Esq",4 S Main St #285,Glenmoral,QLD,07-2679-1774,luz_broccoli@hotmail.com,http://www.wynnmaryellenesq.com.au
46,Janessa,Ruthers,Mackraft Signs,1255 W Passaic St #1553,Bolivia,NSW,02-2367-6845,janessa@yahoo.com,http://www.mackraftsigns.com.au
47,Lavonne,Esco,Ansaring Answering Service,377 Excalibur Dr,East Melbourne,VIC,03-3474-2120,lavonne.esco@yahoo.com,http://www.ansaringansweringservice.com.au
48,Honey,Lymaster,Joiner & Goudeau Law Offices,7 Wilshire Blvd,Taringa,QLD,07-8087-2603,honey_lymaster@lymaster.net.au,http://www.joinergoudeaulawoffices.com.au
49,Jean,Cecchinato,"Cox, J Thomas Jr",7 Hugh Wallis Rd,Koolan Island,WA,08-5263-2786,jean.cecchinato@gmail.com,http://www.coxjthomasjr.com.au
50,Katlyn,Flitcroft,"Bill, Michael M",7177 E 14th St,Maleny,QLD,07-1778-9968,kflitcroft@hotmail.com,http://www.billmichaelm.com.au
51,Cassie,Soros,A B C Tank Co,67765 W 11th St,Yelverton,WA,08-2666-6390,csoros@gmail.com,http://www.abctankco.com.au
52,Rolf,Gene,"Jolley, Mark A Cpa",99968 Merced St #79,Flinders,NSW,02-4458-2810,rolf_gene@gene.com.au,http://www.jolleymarkacpa.com.au
53,Darnell,Moothart,Melco Embroidery Systems,40 E 19th Ave,Empire Bay,NSW,02-3996-9188,darnell_moothart@yahoo.com,http://www.melcoembroiderysystems.com.au
54,Cherilyn,Fraize,Witchs Brew,84826 Plaza Dr,Rose Bay North,NSW,02-4873-1914,cherilyn_fraize@fraize.net.au,http://www.witchsbrew.com.au
55,Lynda,Lazzaro,Funding Equity Corp,20214 W Main St,Macks Creek,VIC,03-4933-4205,lynda.lazzaro@gmail.com,http://www.fundingequitycorp.com.au
56,Leigha,Capelli,Saturn Of Delray,8039 Howard Ave,East Toowoomba,QLD,07-4823-9785,leigha.capelli@capelli.com.au,http://www.saturnofdelray.com.au
57,Delfina,Binnie,Motel 6,8 Austin Bluffs Pky,Bimbijy,WA,08-3692-5784,delfina_binnie@binnie.net.au,http://www.motel.com.au
58,Carlota,Gephardt,Ultimate In Womens Apparel The,96605 Pioneer Rd,Kundabung,NSW,02-5078-4389,carlota.gephardt@gephardt.com.au,http://www.ultimateinwomensapparelthe.com.au
59,Alida,Helger,"Ballinger, Maria Chan Esq",6 Hope Rd #10,Pinnacle,QLD,07-1642-3251,alida@helger.com.au,http://www.ballingermariachanesq.com.au
60,Donte,Resureccion,N E Industrial Distr Inc,65898 E St Nw,Watsonville,QLD,07-2373-6048,donte.resureccion@yahoo.com,http://www.neindustrialdistrinc.com.au
61,Lou,Kriner,"Joondeph, Jerome J Esq",39 Broad St,Seaforth,NSW,02-7328-3350,lou.kriner@hotmail.com,http://www.joondephjeromejesq.com.au
62,Dortha,Vrieze,Art In Forms,654 Seguine Ave,White Hills,TAS,03-1981-6209,dortha@vrieze.net.au,http://www.artinforms.com.au
63,Genevive,Sanborn,Central Hudson Ent Corp,78 31st St,Bellangry,NSW,02-6246-5711,genevive@hotmail.com,http://www.centralhudsonentcorp.com.au
64,Alease,Strawbridge,"Marscher, William F Iii",35673 Annapolis Rd #190,Ascot,QLD,07-3760-1546,alease_strawbridge@strawbridge.com.au,http://www.marscherwilliamfiii.com.au
65,Veda,Mishkin,"Smith, Sean O Esq",98247 Russell Blvd,Stafford Heights,QLD,07-6034-2422,veda.mishkin@mishkin.com.au,http://www.smithseanoesq.com.au
66,Craig,Vandersloot,Maverik Country Stores Inc,3 S Willow St #82,Bygalorie,NSW,02-5487-7528,craig_vandersloot@yahoo.com,http://www.maverikcountrystoresinc.com.au
67,Lauran,Tovmasyan,United Christian Cmnty Crdt Un,199 Maple Ave,Boolaroo,NSW,02-2546-5344,ltovmasyan@tovmasyan.net.au,http://www.unitedchristiancmntycrdtun.com.au
68,Aaron,Kloska,"Radecker, H Philip Jr",423 S Navajo St #56,Brookhill,QLD,07-9896-4827,aaron_kloska@kloska.net.au,http://www.radeckerhphilipjr.com.au
69,Francene,Skursky,"Cullen, Jack J Esq",5 30w W #3083,Hillston,NSW,02-5941-3178,francene.skursky@skursky.net.au,http://www.cullenjackjesq.com.au
70,Zena,Daria,Kszl Am Radio,57245 W Union Blvd #25,Ivanhoe East,VIC,03-2822-8156,zdaria@gmail.com,http://www.kszlamradio.com.au
71,Brigette,Breckenstein,"Blewett, Yvonne S",971 Northwest Blvd,Caniambo,VIC,03-5722-3451,brigette@breckenstein.com.au,http://www.blewettyvonnes.com.au
72,Jeniffer,Jezek,Sheraton Inn Atlanta Northwest,1089 Pacific Coast Hwy,Myrniong,VIC,03-3268-5102,jeniffer@gmail.com,http://www.sheratoninnatlantanorthwest.com.au
73,Selma,Elm,"Preston, Anne M Esq",6787 Emerson St,Woolamai,VIC,03-9183-9493,selm@elm.net.au,http://www.prestonannemesq.com.au
74,Elenora,Handler,A & A Custom Rubber Stamps,8 Middletown Blvd #708,Wardering,WA,08-5671-3318,ehandler@yahoo.com,http://www.aacustomrubberstamps.com.au
75,Nadine,Okojie,"Hirsch, Walter W Esq",56 Tank Farm Rd,Kukerin,WA,08-9746-2341,nadine.okojie@okojie.com.au,http://www.hirschwalterwesq.com.au
76,Kristin,Shiflet,"Jones, Peter B Esq",503 Fulford Ave,Somers,VIC,03-4529-7210,kristin@hotmail.com,http://www.jonespeterbesq.com.au
77,Melinda,Fellhauer,Sterling Institute,8275 Calle De Industrias,Wayatinah,TAS,03-4387-3800,melinda_fellhauer@fellhauer.com.au,http://www.sterlinginstitute.com.au
78,Kirby,Litherland,Cross Western Store,92 South St,Alligator Creek,QLD,07-5284-3845,kirby.litherland@hotmail.com,http://www.crosswesternstore.com.au
79,Kent,Ivans,Demer Normann Smith Ltd,56710 Euclid Ave,Camp Mountain,QLD,07-8661-4016,kent_ivans@yahoo.com,http://www.demernormannsmithltd.com.au
80,Dan,Platz,Ny Stat Trial Lawyers Assn,5210 E Airy St #2,Brandy Creek,QLD,07-4306-1623,dan_platz@hotmail.com,http://www.nystattriallawyersassn.com.au
81,Millie,Pirkl,"Mann, Charles E Esq",31 Schuyler Ave,Sovereign Hill,VIC,03-6023-2680,millie_pirkl@gmail.com,http://www.manncharleseesq.com.au
82,Moira,Qadir,Airnetics Engineering Co,661 Plummer St #963,Arno Bay,SA,08-7687-4883,moira.qadir@gmail.com,http://www.airneticsengineeringco.com.au
83,Reta,Qazi,American Pie Co Inc,1351 Simpson St,Maffra,VIC,03-1974-9948,reta.qazi@yahoo.com,http://www.americanpiecoinc.com.au
84,Brittney,Lolley,Brown Chiropractic,2391 Pacific Blvd,Ulverstone,TAS,03-4072-7094,brittney@lolley.net.au,http://www.brownchiropractic.com.au
85,Leandro,Bolka,Classic Video Duplication Inc,1886 2nd Ave,Wattle Hill,TAS,03-8157-4609,leandro_bolka@hotmail.com,http://www.classicvideoduplicationinc.com.au
86,Edison,Sumera,Mcclier Corp,52404 S Clinton Ave,Bower,SA,08-9114-1763,edison.sumera@sumera.net.au,http://www.mccliercorp.com.au
87,Breana,Cassi,Gormley Lore Murphy,405 W Lee St,Stonehaven,VIC,03-2305-8627,breana@yahoo.com,http://www.gormleyloremurphy.com.au
88,Jarvis,Nicols,Thudium Mail Advg Company,5656 N Fiesta Blvd,East Newdegate,WA,08-2117-5217,jarvis@gmail.com,http://www.thudiummailadvgcompany.com.au
89,Felicitas,Orlinski,Jen E Distributing Co,9 Beverly Rd #5,Emerald,VIC,03-2451-1896,felicitas_orlinski@orlinski.com.au,http://www.jenedistributingco.com.au
90,Geraldine,Neisius,Re/max Realty Services,96 Armitage Ave,Katunga,VIC,03-8243-2999,geraldine@gmail.com,http://www.remaxrealtyservices.com.au
91,Alfred,Pacleb,Roundys Pole Fence Co,523 N Prince St,Willunga,SA,08-9450-7978,alfred@pacleb.net.au,http://www.roundyspolefenceco.com.au
92,Leatha,Block,Chadds Ford Winery,6926 Orange Ave,Two Rocks,WA,08-7635-8350,leatha_block@gmail.com,http://www.chaddsfordwinery.com.au
93,Jacquelyne,Rosso,"Barragar, Anne L Esq",6940 Prospect Pl,Caldwell,NSW,02-4565-6425,jacquelyne.rosso@yahoo.com,http://www.barragarannelesq.com.au
94,Jonelle,Epps,Kvoo Radio,52347 San Fernando Rd,Coppabella,QLD,07-8085-8351,jepps@hotmail.com,http://www.kvooradio.com.au
95,Rosamond,Amlin,"Donovan, William P Esq",5399 Mcwhorter Rd,Calala,NSW,02-8007-5034,rosamond.amlin@gmail.com,http://www.donovanwilliampesq.com.au
96,Johnson,Mcenery,Overseas General Business Co,7 Hall St,Nambucca Heads,NSW,02-1718-4983,johnson@gmail.com,http://www.overseasgeneralbusinessco.com.au
97,Elliot,Scatton,Nilad Machining,5 W Allen St,Mccullys Gap,NSW,02-3647-9507,elliot.scatton@hotmail.com,http://www.niladmachining.com.au
98,Gerri,Perra,"Byrne, Beth Hobbs",15126 Goldenwest St,Toowoomba South,QLD,07-6019-7861,gerri@yahoo.com,http://www.byrnebethhobbs.com.au
99,Rosendo,Jelsma,"Dileo, Lucille A Esq",94 I 55s S,Applecross,WA,08-7712-4785,rosendo_jelsma@hotmail.com,http://www.dileolucilleaesq.com.au
100,Eveline,Brickhouse,First Express,288 N 168th Ave #266,Camberwell West,VIC,03-9517-9800,eveline@yahoo.com,http://www.firstexpress.com.au
101,Laurene,Bennett,Elbin Internatl Baskets,5 Richmond Ct,North Perth,WA,08-2969-2908,laurene_bennett@gmail.com,http://www.elbininternatlbaskets.com.au
102,Tegan,Ebershoff,Multiform Business Printing,28 Aaronwood Ave Ne,Coombell,NSW,02-6604-9720,tegan_ebershoff@hotmail.com,http://www.multiformbusinessprinting.com.au
103,Tracie,Huro,Jin Shin Travel Agency,39701 6th Ave #1485,Pacific Heights,QLD,07-1951-6787,thuro@gmail.com,http://www.jinshintravelagency.com.au
104,Mertie,Kazeck,Electra Gear Divsn Regal,35662 S University Blvd,Guildford,WA,08-5475-6162,mertie.kazeck@kazeck.com.au,http://www.electrageardivsnregal.com.au
105,Clare,Bortignon,Sparta Home Center,73 Dennison St #70,Herron,WA,08-9256-6135,clare_bortignon@hotmail.com,http://www.spartahomecenter.com.au
106,Rebeca,Baley,R A C E Enterprises Inc,9591 Bayshore Rd #637,Mirrool,NSW,02-7049-7728,rebeca_baley@hotmail.com,http://www.raceenterprisesinc.com.au
107,Nilsa,Pawell,Jersey Wholesale Fence Co Inc,57 N Weinbach Ave,Bundaberg West,QLD,07-8997-8513,npawell@pawell.net.au,http://www.jerseywholesalefencecoinc.com.au
108,Samuel,Arellanes,"Ryan, Barry M Esq",286 Santa Rosa Ave,Lane Cove,NSW,02-7995-6787,samuel.arellanes@arellanes.net.au,http://www.ryanbarrymesq.com.au
109,Ivette,Servantes,"Albright, Alexandra W Esq",446 Woodward Ave #1,Reservoir,VIC,03-9801-9429,ivette_servantes@servantes.com.au,http://www.albrightalexandrawesq.com.au
110,Merrilee,Fajen,Gazette Record,1 Jenks Ave,Upper Kedron,QLD,07-9104-1459,merrilee@fajen.net.au,http://www.gazetterecord.com.au
111,Gianna,Eilers,Cochnower Pest Control,7 Valley Blvd,Buchan,VIC,03-4328-5253,gianna@yahoo.com,http://www.cochnowerpestcontrol.com.au
112,Hyman,Phinazee,Als Village Stationers,42741 Anania Dr,Beltana,SA,08-5756-9456,hphinazee@yahoo.com,http://www.alsvillagestationers.com.au
113,Buck,Pascucci,A B C Pattern & Foundry Co,5 Shakespeare Ave,Kingswood,SA,08-9279-1731,buck@yahoo.com,http://www.abcpatternfoundryco.com.au
114,Kenny,Leicht,Gaddis Court Reporting,245 5th Ave,Nicholls Rivulet,TAS,03-6240-8274,kenny@leicht.com.au,http://www.gaddiscourtreporting.com.au
115,Tabetha,Bai,Howard Johnson,2 Gateway Ctr,Upper Mount Gravatt,QLD,07-6813-6477,tabetha.bai@gmail.com,http://www.howardjohnson.com.au
116,Alonso,Popper,Sunrise Cirby Animal Hospital,3175 Northwestern Hwy,Ridgley,TAS,03-7036-7071,alonso_popper@hotmail.com,http://www.sunrisecirbyanimalhospital.com.au
117,Alonzo,Polek,Braid Electric Co,8 S Plaza Dr,Tubbut,VIC,03-2403-7167,alonzo_polek@polek.net.au,http://www.braidelectricco.com.au
118,Son,Magnotta,"Lisko, Roy K Esq",8 Collins Ave,Collingullie,NSW,02-2376-7653,son.magnotta@magnotta.net.au,http://www.liskoroykesq.com.au
119,Jesusita,Druck,House Of Ing,9526 Lincoln St,Munno Para,SA,08-3605-3943,jesusita@druck.net.au,http://www.houseofing.com.au
120,Annice,Kunich,"Hassanein, Nesa E Esq",406 E 4th St,Tyagarah,NSW,02-6769-6153,annice_kunich@kunich.net.au,http://www.hassaneinnesaeesq.com.au
121,Delila,Buchman,Frasier Karen L Kolligs,361 Via Colinas,Redgate,WA,08-1791-7668,delila.buchman@hotmail.com,http://www.frasierkarenlkolligs.com.au
122,Iraida,Sionesini,Arc Of Montgomery County Inc,94 S Jefferson Rd,Modewarre,VIC,03-4812-5654,iraida.sionesini@yahoo.com,http://www.arcofmontgomerycountyinc.com.au
123,Alona,Driesenga,"Redington, Thomas P Esq",8961 S Central Expy,Stirling Range National Park,WA,08-6777-4159,alona_driesenga@hotmail.com,http://www.redingtonthomaspesq.com.au
124,Lajuana,Vonderahe,Milwaukee Courier Inc,7 Wiley Post Way,Trowutta,TAS,03-5661-2424,lajuana.vonderahe@yahoo.com,http://www.milwaukeecourierinc.com.au
125,Madelyn,Maestri,Mervis Steel Co,60 S 4th St,Rouse Hill,NSW,02-2129-8131,madelyn.maestri@yahoo.com,http://www.mervissteelco.com.au
126,Louann,Susmilch,M Sorkin Sanford Associates,6 Lafayette St #3034,Wyandra,QLD,07-5035-4889,louann_susmilch@yahoo.com,http://www.msorkinsanfordassociates.com.au
127,William,Devol,Low Country Kitchen & Bath,35 Jefferson Ave,Goondi Hill,QLD,07-4963-5297,wdevol@devol.net.au,http://www.lowcountrykitchenbath.com.au
128,Corazon,Grafenstein,Spieker Properties,3492 88th St,Hill River,WA,08-1624-7236,cgrafenstein@gmail.com,http://www.spiekerproperties.com.au
129,Fairy,Burket,Walker & Brehn Pa,20 Sw 28th Ter,Fairview Park,SA,08-9159-7562,fairy_burket@burket.com.au,http://www.walkerbrehnpa.com.au
130,Lashawn,Urion,U Stor,6 Argyle Rd,Bar Beach,NSW,02-4794-6673,lurion@yahoo.com,http://www.ustor.com.au
131,Ronald,Gayner,"Moorhead, Michael D Esq",438 E Reynolds Rd #239,University Of Tasmania,TAS,03-7734-9557,rgayner@hotmail.com,http://www.moorheadmichaeldesq.com.au
132,Shizue,Hayduk,R M Sloan Co Inc,47 Hall St,Regent West,VIC,03-2297-9891,shayduk@gmail.com,http://www.rmsloancoinc.com.au
133,Nida,Fitz,Star Limousine,17720 Beach Blvd,Oxley,QLD,07-7445-2572,nfitz@hotmail.com,http://www.starlimousine.com.au
134,Amos,Limberg,Pioneer Telephone Paging,8 2nd St,Don,TAS,03-4539-9131,alimberg@limberg.com.au,http://www.pioneertelephonepaging.com.au
135,Dexter,Prosienski,Communication Buildings Amer,490 Court St,Nyora,VIC,03-2454-6523,dexter@prosienski.net.au,http://www.communicationbuildingsamer.com.au
136,Ludivina,Calamarino,Components & Equipment Co,1456 Hill Rd,Croydon,QLD,07-5378-4498,lcalamarino@yahoo.com,http://www.componentsequipmentco.com.au

# 5)Exploring Data
- **.info()** - gives info of data i.e. column name, dtypes, no. of entries, indexes, not null values, memory usage

In [65]:
print(ex1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   First Name    500 non-null    object
 1   Last Name     500 non-null    object
 2   Company Name  500 non-null    object
 3   Address       500 non-null    object
 4   City          500 non-null    object
 5   State         500 non-null    object
 6   Phone No      500 non-null    object
 7   Email         500 non-null    object
 8   Web           500 non-null    object
dtypes: object(9)
memory usage: 35.3+ KB
None

- **.head()** - top records

In [67]:
print(ex1.head(10)) #will return first 10 records

  First Name   Last Name                    Company Name  \
0   Rebbecca       Didio          Brandt, Jonathan F Esq
1     Stevie       Hallo      Landrum Temporary Services
2     Mariko      Stayer             Inabinet, Macre Esq
3    Gerardo      Woodka        Morris Downing & Sherred
4      Mayra        Bena              Buelt, David L Esq
5     Idella    Scotland  Artesian Ice & Cold Storage Co
6    Sherill        Klar                    Midway Hotel
7        Ena  Desjardiws            Selsor, Robert J Esq
8      Vince       Siena            Vincent J Petti & Co
9     Theron     Jarding            Prentiss, Paul F Esq

                 Address             City State      Phone No  \
0          171 E 24th St            Leith   TAS  03-8174-9123
1         22222 Acoma St          Proston   QLD  07-9997-3366
2  534 Schoenborn St #51            Hamel    WA  08-5558-9019
3      69206 Jackson Ave         Talmalmo   NSW  02-6044-4682
4      808 Glen Cove Ave        Lane Cove   NSW  02-1455-6085
5       373 Lafayette St      Cartmeticup    WA  08-7868-1355
6          87 Sylvan Ave           Nyamup    WA  08-6522-8931
7        60562 Ky Rt 321  Bendick Murrell   NSW  02-5226-9402
8           70 S 18th Pl       Purrawunda   QLD  07-3184-9989
9      8839 Ventura Blvd      Blanchetown    SA  08-6890-4661

                              Email  \
0       rebbecca.didio@didio.com.au
1          stevie.hallo@hotmail.com
2         mariko_stayer@hotmail.com
3        gerardo_woodka@hotmail.com
4              mayra.bena@gmail.com
5                idella@hotmail.com
6                 sklar@hotmail.com
7  ena_desjardiws@desjardiws.com.au
8             vince_siena@yahoo.com
9              tjarding@hotmail.com

                                          Web
0        http://www.brandtjonathanfesq.com.au
1  http://www.landrumtemporaryservices.com.au
2          http://www.inabinetmacreesq.com.au
3      http://www.morrisdowningsherred.com.au
4            http://www.bueltdavidlesq.com.au
5  http://www.artesianicecoldstorageco.com.au
6               http://www.midwayhotel.com.au
7          http://www.selsorrobertjesq.com.au
8           http://www.vincentjpettico.com.au
9          http://www.prentisspaulfesq.com.au

- **.tail()** - bottom records

In [69]:
print(ex1.tail(10)) #will return last 10 records

    First Name Last Name               Company Name                 Address  \
490  Margurite      Okon          Kent, Wendy M Esq          32 Broadway St
491      Artie     Saine          Dixon, Eric D Esq      41 Washington Blvd
492      Major  Studwell      Wood Sign & Banner Co      5 Buford Hwy Ne #3
493   Veronika  Buchauer        Adkins, Russell Esq              6 Flex Ave
494  Christene    Cisney        Danform Shoe Stores      21058 Massillon Rd
495      Miles   Feldner  Antietam Cable Television  28465 Downey Ave #4238
496      Julio     Mikel          Lombardi Bros Inc     2803 N Catalina Ave
497       Aide     Ghera      Nathaniel Electronics       22 Livingston Ave
498     Noelia  Brackett    Rodriguez, Joseph A Esq      403 Conn Valley Rd
499     Lenora  Delacruz    Stilling, William J Esq          5400 Market St

             City State      Phone No                              Email  \
490        Lanena   TAS  03-9721-7313         margurite.okon@hotmail.com
491     Cora Lynn   VIC  03-3457-2524              artie_saine@yahoo.com
492        Allora   QLD  07-1377-6898                    major@gmail.com
493   Willow Tree   NSW  02-4202-5191  veronika.buchauer@buchauer.net.au
494  Keilor Downs   VIC  03-3630-2467              christene@hotmail.com
495     Barringun   QLD  07-8561-5894                  miles@hotmail.com
496       Pilliga   NSW  02-6995-9902           julio.mikel@mikel.net.au
497        Rhodes   NSW  02-3738-7508            aide.ghera@ghera.com.au
498    Castletown    WA  08-3773-3770             noelia@brackett.net.au
499        Turill   NSW  02-7862-5151             lenora@delacruz.net.au

                                           Web
490            http://www.kentwendymesq.com.au
491            http://www.dixonericdesq.com.au
492         http://www.woodsignbannerco.com.au
493         http://www.adkinsrussellesq.com.au
494        http://www.danformshoestores.com.au
495  http://www.antietamcabletelevision.com.au
496          http://www.lombardibrosinc.com.au
497     http://www.nathanielelectronics.com.au
498      http://www.rodriguezjosephaesq.com.au
499      http://www.stillingwilliamjesq.com.au

- **.describe()** - inorder to do statistical analysis of mathematical column we cam use .describe() method

In [71]:
print(ex1.describe())

       First Name Last Name  Company Name        Address           City State  \
count         500       500           500            500            500   500
unique        484       500           498            500            480     8
top        Gerald     Didio  House Of Ing  171 E 24th St  Varsity Lakes   NSW
freq            2         1             2              1              2   125

            Phone No                        Email  \
count            500                          500
unique           500                          500
top     03-8174-9123  rebbecca.didio@didio.com.au
freq               1                            1

                                 Web
count                            500
unique                           498
top     http://www.houseofing.com.au
freq                               2

- **.isnull()** - to find null values

In [73]:
print(ex1.isnull()) #returns TRUE for null values

     First Name  Last Name  Company Name  Address   City  State  Phone No  \
0         False      False         False    False  False  False     False
1         False      False         False    False  False  False     False
2         False      False         False    False  False  False     False
3         False      False         False    False  False  False     False
4         False      False         False    False  False  False     False
5         False      False         False    False  False  False     False
6         False      False         False    False  False  False     False
7         False      False         False    False  False  False     False
8         False      False         False    False  False  False     False
9         False      False         False    False  False  False     False
10        False      False         False    False  False  False     False
11        False      False         False    False  False  False     False
12        False      False         False    False  False  False     False
13        False      False         False    False  False  False     False
14        False      False         False    False  False  False     False
15        False      False         False    False  False  False     False
16        False      False         False    False  False  False     False
17        False      False         False    False  False  False     False
18        False      False         False    False  False  False     False
19        False      False         False    False  False  False     False
20        False      False         False    False  False  False     False
21        False      False         False    False  False  False     False
22        False      False         False    False  False  False     False
23        False      False         False    False  False  False     False
24        False      False         False    False  False  False     False
25        False      False         False    False  False  False     False
26        False      False         False    False  False  False     False
27        False      False         False    False  False  False     False
28        False      False         False    False  False  False     False
29        False      False         False    False  False  False     False
30        False      False         False    False  False  False     False
31        False      False         False    False  False  False     False
32        False      False         False    False  False  False     False
33        False      False         False    False  False  False     False
34        False      False         False    False  False  False     False
35        False      False         False    False  False  False     False
36        False      False         False    False  False  False     False
37        False      False         False    False  False  False     False
38        False      False         False    False  False  False     False
39        False      False         False    False  False  False     False
40        False      False         False    False  False  False     False
41        False      False         False    False  False  False     False
42        False      False         False    False  False  False     False
43        False      False         False    False  False  False     False
44        False      False         False    False  False  False     False
45        False      False         False    False  False  False     False
46        False      False         False    False  False  False     False
47        False      False         False    False  False  False     False
48        False      False         False    False  False  False     False
49        False      False         False    False  False  False     False
50        False      False         False    False  False  False     False
51        False      False         False    False  False  False     False
52        False      False         False    False  False  False     False
53        False      False         False    False  False  False     False
54        False      False         False    False  False  False     False
55        False      False         False    False  False  False     False
56        False      False         False    False  False  False     False
57        False      False         False    False  False  False     False
58        False      False         False    False  False  False     False
59        False      False         False    False  False  False     False
60        False      False         False    False  False  False     False
61        False      False         False    False  False  False     False
62        False      False         False    False  False  False     False
63        False      False         False    False  False  False     False
64        False      False         False    False  False  False     False
65        False      False         False    False  False  False     False
66        False      False         False    False  False  False     False
67        False      False         False    False  False  False     False
68        False      False         False    False  False  False     False
69        False      False         False    False  False  False     False
70        False      False         False    False  False  False     False
71        False      False         False    False  False  False     False
72        False      False         False    False  False  False     False
73        False      False         False    False  False  False     False
74        False      False         False    False  False  False     False
75        False      False         False    False  False  False     False
76        False      False         False    False  False  False     False
77        False      False         False    False  False  False     False
78        False      False         False    False  False  False     False
79        False      False         False    False  False  False     False
80        False      False         False    False  False  False     False
81        False      False         False    False  False  False     False
82        False      False         False    False  False  False     False
83        False      False         False    False  False  False     False
84        False      False         False    False  False  False     False
85        False      False         False    False  False  False     False
86        False      False         False    False  False  False     False
87        False      False         False    False  False  False     False
88        False      False         False    False  False  False     False
89        False      False         False    False  False  False     False
90        False      False         False    False  False  False     False
91        False      False         False    False  False  False     False
92        False      False         False    False  False  False     False
93        False      False         False    False  False  False     False
94        False      False         False    False  False  False     False
95        False      False         False    False  False  False     False
96        False      False         False    False  False  False     False
97        False      False         False    False  False  False     False
98        False      False         False    False  False  False     False
99        False      False         False    False  False  False     False
100       False      False         False    False  False  False     False
101       False      False         False    False  False  False     False
102       False      False         False    False  False  False     False
103       False      False         False    False  False  False     False
104       False      False         False    False  False  False     False
105       False      False         False    False  False  False     False
106       False      False         False    False  False  False     False
107       False      False         False    False  False  False     False
108       False      False         False    False  False  False     False
109       False      False         False    False  False  False     False
110       False      False         False    False  False  False     False
111       False      False         False    False  False  False     False
112       False      False         False    False  False  False     False
113       False      False         False    False  False  False     False
114       False      False         False    False  False  False     False
115       False      False         False    False  False  False     False
116       False      False         False    False  False  False     False
117       False      False         False    False  False  False     False
118       False      False         False    False  False  False     False
119       False      False         False    False  False  False     False
120       False      False         False    False  False  False     False
121       False      False         False    False  False  False     False
122       False      False         False    False  False  False     False
123       False      False         False    False  False  False     False
124       False      False         False    False  False  False     False
125       False      False         False    False  False  False     False
126       False      False         False    False  False  False     False
127       False      False         False    False  False  False     False
128       False      False         False    False  False  False     False
129       False      False         False    False  False  False     False
130       False      False         False    False  False  False     False
131       False      False         False    False  False  False     False
132       False      False         False    False  False  False     False
133       False      False         False    False  False  False     False
134       False      False         False    False  False  False     False
135       False      False         False    False  False  False     False
136       False      False         False    False  False  False     False
137       False      False         False    False  False  False     False
138       False      False         False    False  False  False     False
139       False      False         False    False  False  False     False
140       False      False         False    False  False  False     False
141       False      False         False    False  False  False     False
142       False      False         False    False  False  False     False
143       False      False         False    False  False  False     False
144       False      False         False    False  False  False     False
145       False      False         False    False  False  False     False
146       False      False         False    False  False  False     False
147       False      False         False    False  False  False     False
148       False      False         False    False  False  False     False
149       False      False         False    False  False  False     False
150       False      False         False    False  False  False     False
151       False      False         False    False  False  False     False
152       False      False         False    False  False  False     False
153       False      False         False    False  False  False     False
154       False      False         False    False  False  False     False
155       False      False         False    False  False  False     False
156       False      False         False    False  False  False     False
157       False      False         False    False  False  False     False
158       False      False         False    False  False  False     False
159       False      False         False    False  False  False     False
160       False      False         False    False  False  False     False
161       False      False         False    False  False  False     False
162       False      False         False    False  False  False     False
163       False      False         False    False  False  False     False
164       False      False         False    False  False  False     False
165       False      False         False    False  False  False     False
166       False      False         False    False  False  False     False
167       False      False         False    False  False  False     False
168       False      False         False    False  False  False     False
169       False      False         False    False  False  False     False
170       False      False         False    False  False  False     False
171       False      False         False    False  False  False     False
172       False      False         False    False  False  False     False
173       False      False         False    False  False  False     False
174       False      False         False    False  False  False     False
175       False      False         False    False  False  False     False
176       False      False         False    False  False  False     False
177       False      False         False    False  False  False     False
178       False      False         False    False  False  False     False
179       False      False         False    False  False  False     False
180       False      False         False    False  False  False     False
181       False      False         False    False  False  False     False
182       False      False         False    False  False  False     False
183       False      False         False    False  False  False     False
184       False      False         False    False  False  False     False
185       False      False         False    False  False  False     False
186       False      False         False    False  False  False     False
187       False      False         False    False  False  False     False
188       False      False         False    False  False  False     False
189       False      False         False    False  False  False     False
190       False      False         False    False  False  False     False
191       False      False         False    False  False  False     False
192       False      False         False    False  False  False     False
193       False      False         False    False  False  False     False
194       False      False         False    False  False  False     False
195       False      False         False    False  False  False     False
196       False      False         False    False  False  False     False
197       False      False         False    False  False  False     False
198       False      False         False    False  False  False     False
199       False      False         False    False  False  False     False
200       False      False         False    False  False  False     False
201       False      False         False    False  False  False     False
202       False      False         False    False  False  False     False
203       False      False         False    False  False  False     False
204       False      False         False    False  False  False     False
205       False      False         False    False  False  False     False
206       False      False         False    False  False  False     False
207       False      False         False    False  False  False     False
208       False      False         False    False  False  False     False
209       False      False         False    False  False  False     False
210       False      False         False    False  False  False     False
211       False      False         False    False  False  False     False
212       False      False         False    False  False  False     False
213       False      False         False    False  False  False     False
214       False      False         False    False  False  False     False
215       False      False         False    False  False  False     False
216       False      False         False    False  False  False     False
217       False      False         False    False  False  False     False
218       False      False         False    False  False  False     False
219       False      False         False    False  False  False     False
220       False      False         False    False  False  False     False
221       False      False         False    False  False  False     False
222       False      False         False    False  False  False     False
223       False      False         False    False  False  False     False
224       False      False         False    False  False  False     False
225       False      False         False    False  False  False     False
226       False      False         False    False  False  False     False
227       False      False         False    False  False  False     False
228       False      False         False    False  False  False     False
229       False      False         False    False  False  False     False
230       False      False         False    False  False  False     False
231       False      False         False    False  False  False     False
232       False      False         False    False  False  False     False
233       False      False         False    False  False  False     False
234       False      False         False    False  False  False     False
235       False      False         False    False  False  False     False
236       False      False         False    False  False  False     False
237       False      False         False    False  False  False     False
238       False      False         False    False  False  False     False
239       False      False         False    False  False  False     False
240       False      False         False    False  False  False     False
241       False      False         False    False  False  False     False
242       False      False         False    False  False  False     False
243       False      False         False    False  False  False     False
244       False      False         False    False  False  False     False
245       False      False         False    False  False  False     False
246       False      False         False    False  False  False     False
247       False      False         False    False  False  False     False
248       False      False         False    False  False  False     False
249       False      False         False    False  False  False     False
250       False      False         False    False  False  False     False
251       False      False         False    False  False  False     False
252       False      False         False    False  False  False     False
253       False      False         False    False  False  False     False
254       False      False         False    False  False  False     False
255       False      False         False    False  False  False     False
256       False      False         False    False  False  False     False
257       False      False         False    False  False  False     False
258       False      False         False    False  False  False     False
259       False      False         False    False  False  False     False
260       False      False         False    False  False  False     False
261       False      False         False    False  False  False     False
262       False      False         False    False  False  False     False
263       False      False         False    False  False  False     False
264       False      False         False    False  False  False     False
265       False      False         False    False  False  False     False
266       False      False         False    False  False  False     False
267       False      False         False    False  False  False     False
268       False      False         False    False  False  False     False

In [74]:
print(ex1.isnull().sum()) # if values are not null returns 0

First Name      0
Last Name       0
Company Name    0
Address         0
City            0
State           0
Phone No        0
Email           0
Web             0
dtype: int64

# 6)Handling Duplicates
- Duplicate rows are rows that have been registered more than one time.
- To discover duplicates, we can use the duplicated() method.
- The duplicated() method returns a Boolean values for each row.
### Example
Returns True for every row that is a duplicate, otherwise False:

In [76]:
import pandas as pd
ds1= pd.read_csv('C:/Users/DELL/Desktop/jupyter projects/friends.csv')
ds1

   RollNum      Name  CGPA City    Hobby
0    236.0  Rubaisha  3.55  BWP  Singing
1    240.0   Malaika  3.58  JHL  Dancing
2    251.0    Ayesha  3.21  SWL  Reading
3    243.0    Fariha  3.22  SWL   Baking
4    236.0  Rubaisha  3.55  BWP  Singing
5      NaN    Maryam  3.87  KRC  Reading

In [77]:
ds1['RollNum'].duplicated().sum() #there is only 1 duplicated record on the basis of primary key RollNum

1

In [78]:
ds1['RollNum'].duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
Name: RollNum, dtype: bool

## Removing Duplicates
To remove duplicates, use the drop_duplicates() method.

In [80]:
ds1.drop_duplicates('RollNum')

   RollNum      Name  CGPA City    Hobby
0    236.0  Rubaisha  3.55  BWP  Singing
1    240.0   Malaika  3.58  JHL  Dancing
2    251.0    Ayesha  3.21  SWL  Reading
3    243.0    Fariha  3.22  SWL   Baking
5      NaN    Maryam  3.87  KRC  Reading

# 7)Missing Data / Empty Cells
- Empty cells can potentially give you a wrong result when you analyze data.
## Remove Rows
- One way to deal with empty cells is to remove rows that contain empty cells.
- This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.
### Example
Return a new Data Frame with no empty cells:

In [82]:
import pandas as pd
ds2= pd.read_csv("C:/Users/DELL/Desktop/jupyter projects/friends1.csv")
ds2

   RollNum      Name  CGPA City     Hobby
0      236  Rubaisha  3.55  BWP   Singing
1      240   Malaika  3.58  JHL   Dancing
2      251    Ayesha  3.21  SWL   Reading
3      243    Fariha  3.22  SWL    Baking
4      216    Maryam  3.87  KRC   Reading
5      229   Malaika  3.51  SWL       NaN
6      230   Sabrina  3.33  NaN  painting
7      211     Usman   NaN  LHR   Cycling
8      221       NaN  3.00  FSL   Gymming

In [83]:
ds2.isnull().sum() #identifying null values

RollNum    0
Name       1
CGPA       1
City       1
Hobby      1
dtype: int64

In [84]:
ds2.dropna() #Note: By default, the dropna() method returns a new DataFrame, and will not change the original.

   RollNum      Name  CGPA City    Hobby
0      236  Rubaisha  3.55  BWP  Singing
1      240   Malaika  3.58  JHL  Dancing
2      251    Ayesha  3.21  SWL  Reading
3      243    Fariha  3.22  SWL   Baking
4      216    Maryam  3.87  KRC  Reading

In [85]:
#If you want to change the original DataFrame, use the inplace = True argument

import pandas as pd
ds2= pd.read_csv("C:/Users/DELL/Desktop/jupyter projects/friends1.csv")
ds2

ds2.dropna(inplace=True)
ds2

   RollNum      Name  CGPA City    Hobby
0      236  Rubaisha  3.55  BWP  Singing
1      240   Malaika  3.58  JHL  Dancing
2      251    Ayesha  3.21  SWL  Reading
3      243    Fariha  3.22  SWL   Baking
4      216    Maryam  3.87  KRC  Reading

## Drawback of using dropna() method
- changes the count of employee i.e the correct employee count is 9 but after using dropna() method all rows containing even a single empty cell are being completely deleted from the data set and hence the employee count reduces from 9 to 5 which is not correct
- we cant use dropna() method in all situations, in some cases we have to replace the null values with some data i.e. we have to fill null cells using replace() method

### Replacing empty cells with some values
- Another way of dealing with empty cells is to insert a new value instead.
- This way you do not have to delete entire rows just because of some empty cells.
- The **fillna()** method allows us to replace empty cells with a value:
  #### Example
  Replace NULL values with the number 130:

In [88]:
import pandas as pd
ds3= pd.read_csv("C:/Users/DELL/Desktop/jupyter projects/friends1.csv")
ds3

   RollNum      Name  CGPA City     Hobby
0      236  Rubaisha  3.55  BWP   Singing
1      240   Malaika  3.58  JHL   Dancing
2      251    Ayesha  3.21  SWL   Reading
3      243    Fariha  3.22  SWL    Baking
4      216    Maryam  3.87  KRC   Reading
5      229   Malaika  3.51  SWL       NaN
6      230   Sabrina  3.33  NaN  painting
7      211     Usman   NaN  LHR   Cycling
8      221       NaN  3.00  FSL   Gymming

In [89]:
ds3.fillna(130, inplace= True) #ds3.fillna("running", inplace=True) will store "running" in all null cells irrespective of their data type

In [90]:
ds3

   RollNum      Name    CGPA City     Hobby
0      236  Rubaisha    3.55  BWP   Singing
1      240   Malaika    3.58  JHL   Dancing
2      251    Ayesha    3.21  SWL   Reading
3      243    Fariha    3.22  SWL    Baking
4      216    Maryam    3.87  KRC   Reading
5      229   Malaika    3.51  SWL       130
6      230   Sabrina    3.33  130  painting
7      211     Usman  130.00  LHR   Cycling
8      221       130    3.00  FSL   Gymming

#### replace() method
it can also be done using replace() method

In [92]:
import pandas as pd
ds3= pd.read_csv("C:/Users/DELL/Desktop/jupyter projects/friends1.csv")
ds3

   RollNum      Name  CGPA City     Hobby
0      236  Rubaisha  3.55  BWP   Singing
1      240   Malaika  3.58  JHL   Dancing
2      251    Ayesha  3.21  SWL   Reading
3      243    Fariha  3.22  SWL    Baking
4      216    Maryam  3.87  KRC   Reading
5      229   Malaika  3.51  SWL       NaN
6      230   Sabrina  3.33  NaN  painting
7      211     Usman   NaN  LHR   Cycling
8      221       NaN  3.00  FSL   Gymming

In [93]:
import numpy as np
ds3.replace(np.nan, "running")

   RollNum      Name     CGPA     City     Hobby
0      236  Rubaisha     3.55      BWP   Singing
1      240   Malaika     3.58      JHL   Dancing
2      251    Ayesha     3.21      SWL   Reading
3      243    Fariha     3.22      SWL    Baking
4      216    Maryam     3.87      KRC   Reading
5      229   Malaika     3.51      SWL   running
6      230   Sabrina     3.33  running  painting
7      211     Usman  running      LHR   Cycling
8      221   running      3.0      FSL   Gymming

### Replace Only For Specified Columns
- The example above replaces all empty cells in the whole Data Frame.
- To only replace empty values for one column, specify the column name for the DataFrame:
 #### Example
 Replace NULL values in the "Hobby" columns with the "swiming"

In [95]:
import pandas as pd
ds3= pd.read_csv("C:/Users/DELL/Desktop/jupyter projects/friends1.csv")
ds3

   RollNum      Name  CGPA City     Hobby
0      236  Rubaisha  3.55  BWP   Singing
1      240   Malaika  3.58  JHL   Dancing
2      251    Ayesha  3.21  SWL   Reading
3      243    Fariha  3.22  SWL    Baking
4      216    Maryam  3.87  KRC   Reading
5      229   Malaika  3.51  SWL       NaN
6      230   Sabrina  3.33  NaN  painting
7      211     Usman   NaN  LHR   Cycling
8      221       NaN  3.00  FSL   Gymming

#### fillna():

In [97]:
#ds3["Hobby"].fillna("swiming", inplace = True)
#ds3
ds3.fillna({"Hobby":"swiming"}, inplace=True)
ds3

   RollNum      Name  CGPA City     Hobby
0      236  Rubaisha  3.55  BWP   Singing
1      240   Malaika  3.58  JHL   Dancing
2      251    Ayesha  3.21  SWL   Reading
3      243    Fariha  3.22  SWL    Baking
4      216    Maryam  3.87  KRC   Reading
5      229   Malaika  3.51  SWL   swiming
6      230   Sabrina  3.33  NaN  painting
7      211     Usman   NaN  LHR   Cycling
8      221       NaN  3.00  FSL   Gymming

In [98]:
import pandas as pd
ds3= pd.read_csv("C:/Users/DELL/Desktop/jupyter projects/friends1.csv")
ds3

   RollNum      Name  CGPA City     Hobby
0      236  Rubaisha  3.55  BWP   Singing
1      240   Malaika  3.58  JHL   Dancing
2      251    Ayesha  3.21  SWL   Reading
3      243    Fariha  3.22  SWL    Baking
4      216    Maryam  3.87  KRC   Reading
5      229   Malaika  3.51  SWL       NaN
6      230   Sabrina  3.33  NaN  painting
7      211     Usman   NaN  LHR   Cycling
8      221       NaN  3.00  FSL   Gymming

#### replace():

In [100]:
import numpy as np
ds3["Hobby"]=ds3["Hobby"].replace(np.nan, "swiming")
ds3

   RollNum      Name  CGPA City     Hobby
0      236  Rubaisha  3.55  BWP   Singing
1      240   Malaika  3.58  JHL   Dancing
2      251    Ayesha  3.21  SWL   Reading
3      243    Fariha  3.22  SWL    Baking
4      216    Maryam  3.87  KRC   Reading
5      229   Malaika  3.51  SWL   swiming
6      230   Sabrina  3.33  NaN  painting
7      211     Usman   NaN  LHR   Cycling
8      221       NaN  3.00  FSL   Gymming

##### fill empty cells in city column with "ISBD" using fillna()

In [102]:
#ds3["City"].fillna("ISBD", inplace=True)
#print(ds3)
ds3.fillna({"City":"ISBD"}, inplace=True)
print(ds3)
#import numpy as np
#ds3["City"]=ds3["City"].replace(np.nan, "ISBD")
#print(ds3)

   RollNum      Name  CGPA  City     Hobby
0      236  Rubaisha  3.55   BWP   Singing
1      240   Malaika  3.58   JHL   Dancing
2      251    Ayesha  3.21   SWL   Reading
3      243    Fariha  3.22   SWL    Baking
4      216    Maryam  3.87   KRC   Reading
5      229   Malaika  3.51   SWL   swiming
6      230   Sabrina  3.33  ISBD  painting
7      211     Usman   NaN   LHR   Cycling
8      221       NaN  3.00   FSL   Gymming

#### replace empty cells in CGPA with 3.90 using replace()

In [104]:
import numpy as np
ds3["CGPA"]=ds3["CGPA"].replace(np.nan, 3.90)
ds3

   RollNum      Name  CGPA  City     Hobby
0      236  Rubaisha  3.55   BWP   Singing
1      240   Malaika  3.58   JHL   Dancing
2      251    Ayesha  3.21   SWL   Reading
3      243    Fariha  3.22   SWL    Baking
4      216    Maryam  3.87   KRC   Reading
5      229   Malaika  3.51   SWL   swiming
6      230   Sabrina  3.33  ISBD  painting
7      211     Usman  3.90   LHR   Cycling
8      221       NaN  3.00   FSL   Gymming

## Replace Using Mean, Median, or Mode
- A common way to replace empty cells, is to calculate the mean, median or mode value of the column.
- Pandas uses the mean() median() and mode() methods to calculate the respective values for a specified column:
#### Example
- **i->Calculate the MEAN, and replace any empty values with it:**

In [106]:
import pandas as pd
ds3= pd.read_csv("C:/Users/DELL/Desktop/jupyter projects/friends1.csv")
ds3

   RollNum      Name  CGPA City     Hobby
0      236  Rubaisha  3.55  BWP   Singing
1      240   Malaika  3.58  JHL   Dancing
2      251    Ayesha  3.21  SWL   Reading
3      243    Fariha  3.22  SWL    Baking
4      216    Maryam  3.87  KRC   Reading
5      229   Malaika  3.51  SWL       NaN
6      230   Sabrina  3.33  NaN  painting
7      211     Usman   NaN  LHR   Cycling
8      221       NaN  3.00  FSL   Gymming

In [107]:
x= ds3["CGPA"].mean() #Mean = the average value (the sum of all values divided by number of values).

In [108]:
x

3.40875

In [109]:
import numpy as np
ds3["CGPA"]=ds3["CGPA"].replace(np.nan, x)
ds3

   RollNum      Name     CGPA City     Hobby
0      236  Rubaisha  3.55000  BWP   Singing
1      240   Malaika  3.58000  JHL   Dancing
2      251    Ayesha  3.21000  SWL   Reading
3      243    Fariha  3.22000  SWL    Baking
4      216    Maryam  3.87000  KRC   Reading
5      229   Malaika  3.51000  SWL       NaN
6      230   Sabrina  3.33000  NaN  painting
7      211     Usman  3.40875  LHR   Cycling
8      221       NaN  3.00000  FSL   Gymming

**- Calculate the MEDIAN, and replace any empty values with it**

In [111]:
y= ds3["RollNum"].median() #Median = the value in the middle, after you have sorted all values ascending.
y

230.0

In [112]:
ds3["RollNum"].fillna(y, inplace=True)
ds3

C:\Users\DELL\AppData\Local\Temp\ipykernel_18544\3163243179.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds3["RollNum"].fillna(y, inplace=True)

   RollNum      Name     CGPA City     Hobby
0      236  Rubaisha  3.55000  BWP   Singing
1      240   Malaika  3.58000  JHL   Dancing
2      251    Ayesha  3.21000  SWL   Reading
3      243    Fariha  3.22000  SWL    Baking
4      216    Maryam  3.87000  KRC   Reading
5      229   Malaika  3.51000  SWL       NaN
6      230   Sabrina  3.33000  NaN  painting
7      211     Usman  3.40875  LHR   Cycling
8      221       NaN  3.00000  FSL   Gymming

In [113]:
z=ds3["CGPA"].mode()[0] #Mode = the value that appears most frequently.

In [114]:
z

3.0

### bfill
to fill an empty cell with the value in next lower cell we use backward fill i.e. "bfill" with filllna() method

In [116]:
ds3

   RollNum      Name     CGPA City     Hobby
0      236  Rubaisha  3.55000  BWP   Singing
1      240   Malaika  3.58000  JHL   Dancing
2      251    Ayesha  3.21000  SWL   Reading
3      243    Fariha  3.22000  SWL    Baking
4      216    Maryam  3.87000  KRC   Reading
5      229   Malaika  3.51000  SWL       NaN
6      230   Sabrina  3.33000  NaN  painting
7      211     Usman  3.40875  LHR   Cycling
8      221       NaN  3.00000  FSL   Gymming

In [117]:
#ds3.fillna(method="bfill")
ds3.bfill()

   RollNum      Name     CGPA City     Hobby
0      236  Rubaisha  3.55000  BWP   Singing
1      240   Malaika  3.58000  JHL   Dancing
2      251    Ayesha  3.21000  SWL   Reading
3      243    Fariha  3.22000  SWL    Baking
4      216    Maryam  3.87000  KRC   Reading
5      229   Malaika  3.51000  SWL  painting
6      230   Sabrina  3.33000  LHR  painting
7      211     Usman  3.40875  LHR   Cycling
8      221       NaN  3.00000  FSL   Gymming

### ffill
to fill an empty cell with the value in upper cell we use forward fill i.e. "ffill" with filllna() method

In [119]:
ds3

   RollNum      Name     CGPA City     Hobby
0      236  Rubaisha  3.55000  BWP   Singing
1      240   Malaika  3.58000  JHL   Dancing
2      251    Ayesha  3.21000  SWL   Reading
3      243    Fariha  3.22000  SWL    Baking
4      216    Maryam  3.87000  KRC   Reading
5      229   Malaika  3.51000  SWL       NaN
6      230   Sabrina  3.33000  NaN  painting
7      211     Usman  3.40875  LHR   Cycling
8      221       NaN  3.00000  FSL   Gymming

In [120]:
#ds3.fillna(method="ffill")
ds3.ffill()

   RollNum      Name     CGPA City     Hobby
0      236  Rubaisha  3.55000  BWP   Singing
1      240   Malaika  3.58000  JHL   Dancing
2      251    Ayesha  3.21000  SWL   Reading
3      243    Fariha  3.22000  SWL    Baking
4      216    Maryam  3.87000  KRC   Reading
5      229   Malaika  3.51000  SWL   Reading
6      230   Sabrina  3.33000  SWL  painting
7      211     Usman  3.40875  LHR   Cycling
8      221     Usman  3.00000  FSL   Gymming

## Conclusion:
to conclude, inorder to handle empty cells , dropna() is not the best approach, instead
- in case of numeric data, we can use mean, median and mode methods for handling empty cells
- in case of text data we can use bfill and ffill to handle empty cells
these methods are not accurate but atleast provide us better understanding of data rather than deletion of data

# 8) .loc[] and .iloc[]
## .loc[]
- Pandas DataFrame.loc attribute accesses a group of rows and columns by label(s) or a boolean array in the given Pandas DataFrame.
- **Example 1: Select a Single Row and Column By Label using loc[]**

In [123]:
import pandas as pd
data= {"Name":["Fatima", "Ali", "Hamza","Amna", "Asim"], "Age":[15, 17, 19, 20, 20],"Class":[9, 5,8,12,12], "fav_clr":["black","yellow","green","magenta","purple"]}
df=pd.DataFrame(data, index=['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5'])
df

         Name  Age  Class  fav_clr
Row_1  Fatima   15      9    black
Row_2     Ali   17      5   yellow
Row_3   Hamza   19      8    green
Row_4    Amna   20     12  magenta
Row_5    Asim   20     12   purple

In [124]:
#selecting single row and column
result1=df.loc['Row_4', 'Name']
result1

'Amna'

- **Example 2: Select Multiple Rows and Columns**

In [126]:
result2= df.loc[:, ['Name', 'Class']]
result2

         Name  Class
Row_1  Fatima      9
Row_2     Ali      5
Row_3   Hamza      8
Row_4    Amna     12
Row_5    Asim     12

- **Example 3: Select Between Two Rows or Columns**

In [128]:
#r0w 2 to row 4
print("Selected rows:")
result3=df.loc['Row_2':'Row_4']
print(result3)
print("selected columns:")
result4=df.loc[:, "Age":"fav_clr"]
print(result4)
print("Combining the two:")
result5=df.loc["Row_2":"Row_4", "Age":"fav_clr"]
print(result5)

Selected rows:
        Name  Age  Class  fav_clr
Row_2    Ali   17      5   yellow
Row_3  Hamza   19      8    green
Row_4   Amna   20     12  magenta
selected columns:
       Age  Class  fav_clr
Row_1   15      9    black
Row_2   17      5   yellow
Row_3   19      8    green
Row_4   20     12  magenta
Row_5   20     12   purple
Combining the two:
       Age  Class  fav_clr
Row_2   17      5   yellow
Row_3   19      8    green
Row_4   20     12  magenta

- **Example 4: Select Alternate Rows or Columns**

In [130]:
#alternate rows
print("Selecting alternate rows:")
result6= df.loc[::2]
print(result6)
#alternate columns
print("selecting alternate columns:")
result7= df.loc[:, ::2]
print(result7)
#combining
print("Combining the two:")
result8= df.loc[::2, ::2]
print(result8)

Selecting alternate rows:
         Name  Age  Class fav_clr
Row_1  Fatima   15      9   black
Row_3   Hamza   19      8   green
Row_5    Asim   20     12  purple
selecting alternate columns:
         Name  Class
Row_1  Fatima      9
Row_2     Ali      5
Row_3   Hamza      8
Row_4    Amna     12
Row_5    Asim     12
Combining the two:
         Name  Class
Row_1  Fatima      9
Row_3   Hamza      8
Row_5    Asim     12

- **Example 5: Using Conditions with Pandas loc**

In [132]:
df2= pd.DataFrame({"A": [12, 4, 5, None, 1],
                   "B": [7, 2, 54, 3, None],
                   "C": [20, 16, 11, 3, 8],
                   "D": [14, 3, None, 2, 6]}, index=["row_1", "row_2","row_3","row_4","row_5"])
print(df2)

          A     B   C     D
row_1  12.0   7.0  20  14.0
row_2   4.0   2.0  16   3.0
row_3   5.0  54.0  11   NaN
row_4   NaN   3.0   3   2.0
row_5   1.0   NaN   8   6.0

In [133]:
#Select rows where column 'A' is greater than 5
print("rows where column 'A' is greater than 5:")
result9= df2.loc[df2['A']>5]
print(result9)
#Select rows where column 'B' is not null
print("rows where column 'B' is not null")
result10= df2.loc[df2['B'].notnull()]
print(result10)

rows where column 'A' is greater than 5:
          A    B   C     D
row_1  12.0  7.0  20  14.0
rows where column 'B' is not null
          A     B   C     D
row_1  12.0   7.0  20  14.0
row_2   4.0   2.0  16   3.0
row_3   5.0  54.0  11   NaN
row_4   NaN   3.0   3   2.0

## .iloc[]
- In the Python Pandas library, .iloc[] is an indexer used for integer-location-based indexing of data in a DataFrame.
- It allows users to select specific rows and columns by providing integer indices, making it a valuable tool for data manipulation and extraction based on numerical positions within the DataFrame.
- This indexer is particularly useful when you want to access or manipulate data using integer-based positional indexing rather than labels.
- **Example 1: Selecting rows using Pandas .iloc and .loc[]**

In [135]:
import pandas as pd
data= pd.read_csv("C:/Users/DELL/Downloads/nba.csv")
#using loc[]
print("retrieving row 3 using loc[] method:")
rloc= data.loc[3]
print(rloc)
#using iloc[]
print("retrieving row 3 using iloc[] method:")
riloc= data.iloc[3]
print(riloc)
#checking both
print("Checking if both results are same or not:")
rloc == riloc

retrieving row 3 using loc[] method:
Name           R.J. Hunter
Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: 3, dtype: object
retrieving row 3 using iloc[] method:
Name           R.J. Hunter
Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: 3, dtype: object
Checking if both results are same or not:

Name        True
Team        True
Number      True
Position    True
Age         True
Height      True
Weight      True
College     True
Salary      True
Name: 3, dtype: bool

- **Example 2: Selecting Multiple Rows using Pandas .iloc[] in Python**

In [137]:
#through list
print("Selecting multiple rows by passing a list:")
res1= data.iloc[[4,5,6,7]]
print(res1)
#range method
print("Selecting multiple rows using range method:")
res2= data.iloc[4:8]
print(res2)
#checking results
print("Checking if both results are same:")
res1 == res2

Selecting multiple rows by passing a list:
            Name            Team  Number Position   Age Height  Weight  \
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5   Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
6  Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0
7   Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0

   College      Salary
4      NaN   5000000.0
5      NaN  12000000.0
6      LSU   1170960.0
7  Gonzaga   2165160.0
Selecting multiple rows using range method:
            Name            Team  Number Position   Age Height  Weight  \
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5   Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
6  Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0
7   Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0

   College      Salary
4      NaN   5000000.0
5      NaN  12000000.0
6      LSU   1170960.0
7  Gonzaga   2165160.0
Checking if both results are same:

   Name  Team  Number  Position   Age  Height  Weight  College  Salary
4  True  True    True      True  True    True    True    False    True
5  True  True    True      True  True    True    True    False    True
6  True  True    True      True  True    True    True     True    True
7  True  True    True      True  True    True    True     True    True

***All values are True except values in the college column since those were NaN values***

**Example 3: Select Rows by Name or Index usingPandas .iloc[]**

In [140]:
print("original data\n", df)
# Extracting a single row by index
print("Extracting a single row by index:")
res3= df.iloc[0, :]
print(res3)
# Extracting multiple rows using a slice
print("Extracting multiple rows using a slice:")
res4= df.iloc[1:3, :]
print(res4)

original data
          Name  Age  Class  fav_clr
Row_1  Fatima   15      9    black
Row_2     Ali   17      5   yellow
Row_3   Hamza   19      8    green
Row_4    Amna   20     12  magenta
Row_5    Asim   20     12   purple
Extracting a single row by index:
Name       Fatima
Age            15
Class           9
fav_clr     black
Name: Row_1, dtype: object
Extracting multiple rows using a slice:
        Name  Age  Class fav_clr
Row_2    Ali   17      5  yellow
Row_3  Hamza   19      8   green

# 9)Column Transformation Part 1

In [142]:
import pandas as pd
df= pd.read_excel("C:/Users/DELL/Downloads/ESD.xlsx")
df

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT
5,E00644,Joshua Gupta,Account Representative,Sales,Corporate,Male,Asian,57,2017-01-24,50994,0.00,China,Chongqing,NaT
6,E01550,Ruby Barnes,Manager,IT,Corporate,Female,Caucasian,27,2020-07-01,119746,0.10,United States,Phoenix,NaT
7,E04332,Luke Martin,Analyst,Finance,Manufacturing,Male,Black,25,2020-05-16,41336,0.00,United States,Miami,2021-05-20
8,E04533,Easton Bailey,Manager,Accounting,Manufacturing,Male,Caucasian,29,2019-01-25,113527,0.06,United States,Austin,NaT
9,E03838,Madeline Walker,Sr. Analyst,Finance,Speciality Products,Female,Caucasian,34,2018-06-13,77203,0.00,United States,Chicago,NaT
10,E00591,Savannah Ali,Sr. Manger,Human Resources,Manufacturing,Female,Asian,36,2009-02-11,157333,0.15,United States,Miami,NaT
11,E03344,Camila Rogers,Controls Engineer,Engineering,Speciality Products,Female,Caucasian,27,2021-10-21,109851,0.00,United States,Seattle,NaT
12,E00530,Eli Jones,Manager,Human Resources,Manufacturing,Male,Caucasian,59,1999-03-14,105086,0.09,United States,Austin,NaT
13,E04239,Everleigh Ng,Sr. Manger,Finance,Research & Development,Female,Asian,51,2021-06-10,146742,0.10,China,Shanghai,NaT
14,E03496,Robert Yang,Sr. Analyst,Accounting,Speciality Products,Male,Asian,31,2017-11-04,97078,0.00,United States,Austin,2020-03-09
15,E00549,Isabella Xi,Vice President,Marketing,Research & Development,Female,Asian,41,2013-03-13,249270,0.30,United States,Seattle,NaT
16,E00163,Bella Powell,Director,Finance,Research & Development,Female,Black,65,2002-03-04,175837,0.20,United States,Phoenix,NaT
17,E00884,Camila Silva,Sr. Manger,Marketing,Speciality Products,Female,Latino,64,2003-12-01,154828,0.13,United States,Seattle,NaT
18,E04116,David Barnes,Director,IT,Corporate,Male,Caucasian,64,2013-11-03,186503,0.24,United States,Columbus,NaT
19,E04625,Adam Dang,Director,Sales,Research & Development,Male,Asian,45,2002-07-09,166331,0.18,China,Chongqing,NaT
20,E03680,Elias Alvarado,Sr. Manger,IT,Manufacturing,Male,Latino,56,2012-01-09,146140,0.10,Brazil,Manaus,NaT
21,E04732,Eva Rivera,Director,Sales,Manufacturing,Female,Latino,36,2021-04-02,151703,0.21,United States,Miami,NaT
22,E03484,Logan Rivera,Director,IT,Research & Development,Male,Latino,59,2002-05-24,172787,0.28,Brazil,Rio de Janerio,NaT
23,E00671,Leonardo Dixon,Analyst,Sales,Speciality Products,Male,Caucasian,37,2019-09-05,49998,0.00,United States,Seattle,NaT
24,E02071,Mateo Her,Vice President,Sales,Speciality Products,Male,Asian,44,2014-03-02,207172,0.31,China,Chongqing,NaT
25,E02206,Jose Henderson,Director,Human Resources,Speciality Products,Male,Black,41,2015-04-17,152239,0.23,United States,Columbus,NaT
26,E04545,Abigail Mejia,Quality Engineer,Engineering,Corporate,Female,Latino,56,2005-02-05,98581,0.00,Brazil,Rio de Janerio,NaT
27,E00154,Wyatt Chin,Vice President,Engineering,Speciality Products,Male,Asian,43,2004-06-07,246231,0.31,United States,Seattle,NaT
28,E03343,Carson Lu,Engineering Manager,Engineering,Speciality Products,Male,Asian,64,1996-12-04,99354,0.12,China,Beijing,NaT
29,E00304,Dylan Choi,Vice President,IT,Corporate,Male,Asian,63,2012-05-11,231141,0.34,China,Beijing,NaT
30,E02594,Ezekiel Kumar,IT Coordinator,IT,Research & Development,Male,Asian,28,2017-06-25,54775,0.00,United States,Columbus,NaT
31,E00402,Dominic Guzman,Analyst,Finance,Manufacturing,Male,Latino,65,2004-05-16,55499,0.00,Brazil,Manaus,NaT
32,E01994,Angel Powell,Analyst II,Sales,Research & Development,Male,Caucasian,61,2008-07-11,66521,0.00,United States,Seattle,NaT
33,E03549,Mateo Vu,Account Representative,Sales,Speciality Products,Male,Asian,30,2016-09-29,59100,0.00,China,Chongqing,NaT
34,E03247,Caroline Jenkins,Analyst,Finance,Research & Development,Female,Caucasian,27,2018-05-06,49011,0.00,United States,Chicago,NaT
35,E02074,Nora Brown,Enterprise Architect,IT,Manufacturing,Female,Caucasian,32,2014-02-11,99575,0.00,United States,Austin,NaT
36,E04152,Adeline Huang,Controls Engineer,Engineering,Manufacturing,Female,Asian,34,2019-12-16,99989,0.00,China,Chengdu,NaT
37,E01628,Jackson Perry,Vice President,Marketing,Research & Development,Male,Caucasian,27,2019-10-20,256420,0.30,United States,Phoenix,NaT
38,E04285,Riley Padilla,Technical Architect,IT,Manufacturing,Female,Latino,35,2013-05-15,78940,0.00,United States,Miami,NaT
39,E01417,Leah Pena,Enterprise Architect,IT,Corporate,Female,Latino,57,1994-01-03,82872,0.00,Brazil,Manaus,NaT
40,E01754,Owen Lam,Sr. Business Partner,Human Resources,Speciality Products,Male,Asian,30,2017-05-29,86317,0.00,China,Chengdu,2017-07-16
41,E03749,Kennedy Foster,Manager,Marketing,Speciality Products,Female,Caucasian,53,2013-11-23,113135,0.05,United States,Austin,NaT
42,E03574,John Moore,Vice President,IT,Speciality Products,Male,Caucasian,52,2005-11-08,199808,0.32,United States,Seattle,NaT
43,E04600,William Vu,Account Representative,Sales,Speciality Products,Male,Asian,37,2013-11-14,56037,0.00,China,Shanghai,NaT
44,E00586,Sadie Washington,Sr. Manger,Marketing,Research & Development,Female,Caucasian,29,2019-05-24,122350,0.12,United States,Phoenix,NaT
45,E03538,Gabriel Holmes,Enterprise Architect,IT,Research & Development,Male,Caucasian,40,2010-11-04,92952,0.00,United States,Seattle,NaT
46,E02185,Wyatt Rojas,Computer Systems Manager,IT,Corporate,Male,Latino,32,2013-03-20,79921,0.05,United States,Austin,NaT
47,E03830,Eva Coleman,Director,IT,Research & Development,Female,Black,37,2009-09-20,167199,0.20,United States,Seattle,NaT
48,E03720,Dominic Clark,Quality Engineer,Engineering,Research & Development,Male,Caucasian,52,2012-10-17,71476,0.00,United States,Phoenix,NaT
49,E03025,Lucy Alexander,Director,Engineering,Manufacturing,Female,Caucasian,45,2014-10-29,189420,0.20,United States,Seattle,NaT
50,E04917,Everleigh Washington,HRIS Analyst,Human Resources,Research & Development,Female,Caucasian,64,2001-10-20,64057,0.00,United States,Phoenix,NaT
51,E00415,Leilani Butler,Analyst II,Marketing,Manufacturing,Female,Black,27,2021-09-21,68728,0.00,United States,Phoenix,NaT
52,E02862,Peyton Huang,Sr. Manger,IT,Manufacturing,Female,Asian,25,2021-07-02,125633,0.11,China,Beijing,NaT
53,E04207,John Contreras,Analyst II,Marketing,Manufacturing,Male,Latino,35,2011-05-15,66889,0.00,United States,Columbus,NaT
54,E02139,Rylee Yu,Director,Accounting,Research & Development,Female,Asian,36,2015-09-29,178700,0.29,United States,Seattle,NaT
55,E01797,Piper Lewis,Field Engineer,Engineering,Research & Development,Female,Caucasian,33,2018-12-22,83990,0.00,United States,Chicago,NaT
56,E01839,Stella Alexander,Automation Engineer,Engineering,Corporate,Female,Caucasian,52,2005-12-10,102043,0.00,United States,Chicago,NaT
57,E01633,Addison Do,Operations Engineer,Engineering,Manufacturing,Female,Asian,46,2001-05-30,90678,0.00,United States,Columbus,NaT
58,E01848,Zoey Jackson,Business Partner,Human Resources,Manufacturing,Female,Black,46,2008-08-21,59067,0.00,United States,Miami,NaT
59,E00716,John Chow,Sr. Manger,Marketing,Research & Development,Male,Asian,45,2021-03-11,135062,0.15,China,Chengdu,NaT
60,E00699,Ava Ayala,Sr. Manger,IT,Corporate,Female,Latino,55,2006-08-16,159044,0.10,Brazil,Manaus,NaT
61,E00502,Natalia Salazar,Sr. Analyst,Accounting,Manufacturing,Female,Latino,44,2019-01-02,74691,0.00,Brazil,Manaus,2020-07-08
62,E04000,Skylar Carrillo,Engineering Manager,Engineering,Corporate,Female,Latino,44,2008-12-18,92753,0.13,United States,Austin,2021-06-24
63,E02112,Christian Sanders,Vice President,Human Resources,Speciality Products,Male,Black,45,2013-08-07,236946,0.37,United States,Seattle,NaT
64,E03824,Penelope Coleman,Analyst,Finance,Corporate,Female,Black,36,2021-08-27,48906,0.00,United States,Miami,NaT
65,E03906,Piper Richardson,Sr. Analyst,Sales,Corporate,Female,Caucasian,38,2008-01-27,80024,0.00,United States,Columbus,NaT
66,E00436,Everly Walker,HRIS Analyst,Human Resources,Speciality Products,Female,Caucasian,41,2009-10-23,54415,0.00,United States,Seattle,2014-01-22
67,E04798,Aurora Ali,Manager,Marketing,Research & Development,Female,Asian,30,2016-04-24,120341,0.07,United States,Seattle,NaT
68,E01249,Penelope Guerrero,Vice President,IT,Speciality Products,Female,Latino,43,2009-08-04,208415,0.35,United States,Seattle,NaT
69,E03349,Anna Mehta,Cloud Infrastructure Architect,IT,Speciality Products,Female,Asian,32,2020-01-05,78844,0.00,United States,Seattle,NaT
70,E02966,William Foster,Field Engineer,Engineering,Manufacturing,Male,Caucasian,58,2002-05-23,76354,0.00,United States,Phoenix,2021-09-26
71,E01499,Jade Rojas,Director,Finance,Speciality Products,Female,Latino,37,2019-01-28,165927,0.20,United States,Phoenix,NaT
72,E00105,Isla Espinoza,Manager,Accounting,Speciality Products,Female,Latino,38,2021-11-16,109812,0.09,Brazil,Manaus,NaT
73,E00665,David Chu,Controls Engineer,Engineering,Corporate,Male,Asian,55,1998-09-03,86299,0.00,United States,Seattle,NaT
74,E00791,Thomas Padilla,Vice President,Marketing,Research & Development,Male,Latino,57,2003-07-26,206624,0.40,Brazil,Sao Paulo,NaT
75,E01540,Miles Salazar,IT Coordinator,IT,Manufacturing,Male,Latino,36,2010-12-23,53215,0.00,Brazil,Sao Paulo,2014-03-27
76,E04474,Mila Hong,Test Engineer,Engineering,Research & Development,Female,Asian,30,2017-05-22,86858,0.00,China,Chongqing,2017-10-08
77,E03417,Benjamin Moua,Computer Systems Manager,IT,Manufacturing,Male,Asian,40,2007-07-02,93971,0.08,China,Chongqing,NaT
78,E00254,Samuel Morales,Analyst II,Finance,Corporate,Male,Latino,34,2015-06-27,57008,0.00,United States,Phoenix,NaT
79,E02166,John Soto,Sr. Manger,Finance,Manufacturing,Male,Latino,60,2015-09-23,141899,0.15,United States,Phoenix,NaT
80,E00935,Joseph Martin,Analyst II,Marketing,Corporate,Male,Black,41,2016-09-13,64847,0.00,United States,Miami,NaT
81,E01525,Jose Ross,Engineering Manager,Engineering,Research & Development,Male,Caucasian,53,1992-04-08,116878,0.11,United States,Miami,NaT
82,E00386,Parker James,Quality Engineer,Engineering,Speciality Products,Male,Black,45,2005-02-05,70505,0.00,United States,Austin,NaT
83,E00416,Everleigh Fernandez,Director,Engineering,Research & Development,Female,Latino,30,2016-05-22,189702,0.28,Brazil,Manaus,2020-12-21
84,E03383,Lincoln Hall,Director,Accounting,Speciality Products,Male,Caucasian,26,2020-07-28,180664,0.27,United States,Chicago,NaT
85,E01516,Willow Mai,Business Partner,Human Resources,Manufacturing,Female,Asian,45,2003-12-17,48345,0.00,China,Chengdu,NaT
86,E01234,Jack Cheng,Director,Human Resources,Manufacturing,Male,Asian,42,2014-01-16,152214,0.30,China,Beijing,NaT
87,E03440,Genesis Navarro,Cloud Infrastructure Architect,IT,Corporate,Female,Latino,41,2009-04-28,69803,0.00,Brazil,Manaus,NaT
88,E00431,Eliza Hernandez,Network Architect,IT,Corporate,Female,Latino,48,2019-07-04,76588,0.00,Brazil,Rio de Janerio,NaT
89,E01258,Gabriel Brooks,Network Engineer,IT,Manufacturing,Male,Caucasian,29,2018-12-10,84596,0.00,United States,Miami,NaT
90,E00440,Jack Huynh,Manager,Marketing,Research & Development,Male,Asian,27,2018-09-25,114441,0.10,China,Chongqing,2019-12-22
91,E00595,Everly Chow,Sr. Manger,Finance,Speciality Products,Female,Asian,33,2018-04-21,140402,0.15,China,Beijing,NaT
92,E00972,Amelia Salazar,Analyst II,Finance,Corporate,Female,Latino,26,2019-04-23,59817,0.00,Brazil,Sao Paulo,NaT
93,E04562,Xavier Zheng,Account Representative,Sales,Manufacturing,Male,Asian,31,2017-07-22,55854,0.00,United States,Austin,NaT
94,E02802,Matthew Chau,Sr. Business Partner,Human Resources,Research & Development,Male,Asian,53,2002-11-16,95998,0.00,United States,Seattle,NaT
95,E01427,Mia Cheng,Sr. Manger,Sales,Manufacturing,Female,Asian,34,2015-04-22,154941,0.13,United States,Phoenix,NaT
96,E04568,Rylee Yu,Vice President,Finance,Speciality Products,Female,Asian,54,2011-07-10,247022,0.30,China,Beijing,NaT
97,E04931,Zoe Romero,Network Architect,IT,Manufacturing,Female,Latino,32,2021-10-05,88072,0.00,Brazil,Sao Paulo,NaT
98,E00443,Nolan Bui,Computer Systems Manager,IT,Research & Development,Male,Asian,28,2020-05-26,67925,0.08,China,Shanghai,NaT
99,E03890,Nevaeh Jones,Vice President,Sales,Manufacturing,Female,Caucasian,31,2020-08-20,219693,0.30,United States,Austin,NaT
100,E01194,Samantha Adams,Test Engineer,Engineering,Research & Development,Female,Caucasian,45,2013-04-22,61773,0.00,United States,Seattle,NaT
101,E02875,Madeline Shin,Computer Systems Manager,IT,Speciality Products,Female,Asian,48,2007-01-09,74546,0.09,United States,Seattle,NaT
102,E04959,Noah King,Development Engineer,Engineering,Speciality Products,Male,Black,56,2015-01-27,62575,0.00,United States,Miami,NaT
103,E03816,Leilani Chow,Director,Human Resources,Corporate,Female,Asian,27,2021-02-23,199041,0.16,China,Beijing,NaT
104,E01261,Connor Simmons,Analyst II,Accounting,Speciality Products,Male,Caucasian,55,2007-04-05,52310,0.00,United States,Miami,2018-10-12
105,E03612,Grayson Cooper,Sr. Manger,Finance,Speciality Products,Male,Black,64,2013-06-29,159571,0.10,United States,Columbus,NaT
106,E01388,Ivy Soto,Field Engineer,Engineering,Research & Development,Female,Latino,50,1997-10-23,91763,0.00,United States,Austin,NaT
107,E03875,Aurora Simmons,Development Engineer,Engineering,Corporate,Female,Caucasian,51,1995-12-22,96475,0.00,United States,Austin,NaT
108,E04413,Andrew Thomas,Controls Engineer,Engineering,Manufacturing,Male,Caucasian,36,2016-12-02,113781,0.00,United States,Columbus,NaT
109,E00691,Ezekiel Desai,Director,Finance,Research & Development,Male,Asian,42,2003-01-15,166599,0.26,United States,Seattle,NaT
110,E03047,Gabriella Gupta,Sr. Account Representative,Sales,Corporate,Female,Asian,41,2005-02-15,95372,0.00,China,Shanghai,NaT
111,E04903,Skylar Liu,Director,IT,Research & Development,Female,Asian,29,2020-08-09,161203,0.15,China,Chengdu,NaT
112,E04735,Nova Coleman,System Administrator,IT,Manufacturing,Female,Caucasian,44,2006-12-13,74738,0.00,United States,Miami,NaT
113,E02850,Evelyn Dinh,Director,Sales,Research & Development,Female,Asian,41,2018-08-10,171173,0.21,United States,Columbus,NaT
114,E03583,Brooks Marquez,Vice President,Sales,Corporate,Male,Latino,61,2019-09-24,201464,0.37,United States,Chicago,NaT
115,E02017,Connor Joseph,Director,Human Resources,Corporate,Male,Caucasian,50,1998-07-22,174895,0.15,United States,Chicago,NaT
116,E01642,Mia Lam,Sr. Manger,IT,Manufacturing,Female,Asian,49,2006-04-18,134486,0.14,United States,Austin,NaT
117,E04379,Scarlett Rodriguez,Sr. Analyst,Finance,Manufacturing,Female,Latino,60,2007-02-24,71699,0.00,Brazil,Manaus,NaT
118,E04131,Cora Rivera,Sr. Analyst,Marketing,Corporate,Female,Latino,42,2021-01-02,94430,0.00,United States,Seattle,NaT
119,E02872,Liam Jung,Manager,Finance,Corporate,Male,Asian,39,2010-01-14,103504,0.07,China,Chengdu,NaT
120,E02331,Sophia Huynh,Enterprise Architect,IT,Manufacturing,Female,Asian,55,2005-08-09,92771,0.00,United States,Miami,NaT
121,E00417,Athena Carrillo,Analyst II,Finance,Speciality Products,Female,Latino,39,2006-04-06,71531,0.00,United States,Columbus,NaT
122,E04267,Greyson Sanders,Cloud Infrastructure Architect,IT,Speciality Products,Male,Black,28,2019-03-06,90304,0.00,United States,Chicago,NaT
123,E03061,Vivian Lewis,Manager,Marketing,Manufacturing,Female,Caucasian,65,2011-09-07,104903,0.10,United States,Columbus,NaT
124,E00013,Elena Vang,Analyst,Finance,Corporate,Female,Asian,52,2019-02-19,55859,0.00,China,Beijing,NaT
125,E04265,Natalia Diaz,Operations Engineer,Engineering,Corporate,Female,Latino,62,2006-10-12,79785,0.00,United States,Austin,NaT
126,E04769,Mila Leung,Sr. Analyst,Marketing,Corporate,Female,Asian,39,2007-11-05,99017,0.00,China,Beijing,NaT
127,E03042,Ava Nelson,Systems Analyst,IT,Manufacturing,Female,Caucasian,63,1992-04-01,53809,0.00,United States,Phoenix,NaT
128,E00527,Mateo Chu,Field Engineer,Engineering,Speciality Products,Male,Asian,27,2020-04-16,71864,0.00,China,Chengdu,NaT
129,E01095,Isla Lai,Vice President,Finance,Corporate,Female,Asian,37,2011-12-06,225558,0.33,China,Shanghai,NaT
130,E03131,Ezekiel Reed,Sr. Manger,IT,Manufacturing,Male,Caucasian,37,2014-02-25,128984,0.12,United States,Miami,2021-05-01
131,E01713,Nolan Guzman,Field Engineer,Engineering,Speciality Products,Male,Latino,46,1999-06-20,96997,0.00,Brazil,Sao Paulo,NaT
132,E00128,Everleigh Espinoza,Director,Human Resources,Manufacturing,Female,Latino,54,2018-01-22,176294,0.28,United States,Austin,NaT
133,E03849,Evelyn Jung,Analyst,Sales,Research & Development,Female,Asian,30,2021-02-14,48340,0.00,China,Beijing,NaT
134,E02464,Sophie Silva,Vice President,Engineering,Corporate,Female,Latino,28,2017-07-06,240488,0.40,Brazil,Rio de Janerio,NaT
135,E00306,Mateo Williams,Enterprise Architect,IT,Manufacturing,Male,Caucasian,40,2011-01-22,97339,0.00,United States,Austin,NaT
136,E03737,Kennedy Rahman,Vice President,Human Resources,Manufacturing,Female,Asian,49,2003-02-28,211291,0.37,China,Chongqing,NaT
137,E02783,Levi Mendez,Vice President,Sales,Research & Development,Male,Latino,39,2011-08-23,249506,0.30,Brazil,Rio de Janerio,NaT
138,E02939,Julian Fong,Quality Engineer,Engineering,Speciality Products,Male,Asian,61,2002-11-22,80950,0.00,China,Chongqing,NaT
139,E02706,Nevaeh Kang,Automation Engineer,Engineering,Research & Development,Female,Asian,46,2021-01-10,86538,0.00,China,Chengdu,NaT
140,E00170,Hannah Nelson,Sr. Analyst,Marketing,Speciality Products,Female,Caucasian,35,2019-09-07,70992,0.00,United States,Austin,NaT
141,E01425,Anthony Rogers,Vice President,Engineering,Corporate,Male,Caucasian,33,2015-06-18,205314,0.30,United States,Columbus,NaT
142,E00130,Paisley Kang,Vice President,Human Resources,Corporate,Female,Asian,61,2017-03-10,196951,0.33,China,Beijing,NaT
143,E02094,Matthew Gupta,Network Engineer,IT,Speciality Products,Male,Asian,45,2005-09-18,67686,0.00,China,Beijing,NaT
144,E03567,Silas Chavez,Technical Architect,IT,Research & Development,Male,Latino,51,2008-04-15,86431,0.00,United States,Columbus,NaT
145,E04682,Colton Thao,Manager,Human Resources,Manufacturing,Male,Asian,55,1995-11-16,125936,0.08,China,Chongqing,NaT
146,E00957,Genesis Perry,Sr. Manger,Sales,Corporate,Female,Caucasian,46,2013-07-18,149712,0.14,United States,Columbus,NaT
147,E04458,Alexander Bryant,Field Engineer,Engineering,Speciality Products,Male,Caucasian,30,2021-10-02,88758,0.00,United States,Seattle,NaT
148,E01499,Elias Zhang,Solutions Architect,IT,Research & Development,Male,Asian,54,2013-07-13,83639,0.00,China,Beijing,NaT
149,E00521,Lily Carter,Network Architect,IT,Research & Development,Female,Caucasian,54,1998-05-18,68268,0.00,United States,Phoenix,NaT
150,E03717,Joseph Ruiz,Field Engineer,Engineering,Manufacturing,Male,Latino,45,2002-02-26,75819,0.00,Brazil,Sao Paulo,NaT
151,E01533,Avery Bailey,Sr. Analyst,Sales,Speciality Products,Female,Caucasian,49,1996-05-15,86658,0.00,United States,Phoenix,NaT
152,E04449,Miles Hsu,Analyst II,Finance,Research & Development,Male,Asian,55,2014-03-16,74552,0.00,China,Chengdu,NaT
153,E02855,Piper Cheng,Enterprise Architect,IT,Manufacturing,Female,Asian,62,2009-03-15,82839,0.00,United States,Miami,NaT
154,E00816,Skylar Watson,Network Architect,IT,Speciality Products,Female,Caucasian,28,2021-10-08,64475,0.00,United States,Phoenix,NaT
155,E02283,Jaxon Park,Network Architect,IT,Manufacturing,Male,Asian,33,2020-07-24,69453,0.00,China,Chengdu,NaT
156,E04888,Elijah Henry,Manager,IT,Corporate,Male,Caucasian,32,2014-01-03,127148,0.10,United States,Miami,NaT

***Now we will check how many employees get bonus and how many of them don't and store this info in new column "GetBonus"***

In [144]:
df.loc[(df["Bonus %"]==0), "GetBonus"]= "no bonus"
df.loc[(df["Bonus %"]>0), "GetBonus"]="bonus"
df.head(10)

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,GetBonus
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16,bonus
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT,no bonus
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT,bonus
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT,bonus
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT,no bonus
5,E00644,Joshua Gupta,Account Representative,Sales,Corporate,Male,Asian,57,2017-01-24,50994,0.00,China,Chongqing,NaT,no bonus
6,E01550,Ruby Barnes,Manager,IT,Corporate,Female,Caucasian,27,2020-07-01,119746,0.10,United States,Phoenix,NaT,bonus
7,E04332,Luke Martin,Analyst,Finance,Manufacturing,Male,Black,25,2020-05-16,41336,0.00,United States,Miami,2021-05-20,no bonus
8,E04533,Easton Bailey,Manager,Accounting,Manufacturing,Male,Caucasian,29,2019-01-25,113527,0.06,United States,Austin,NaT,bonus
9,E03838,Madeline Walker,Sr. Analyst,Finance,Speciality Products,Female,Caucasian,34,2018-06-13,77203,0.00,United States,Chicago,NaT,no bonus

***Combining 2 or more columns using + operator***

In [146]:
import pandas as pd
data= pd.read_csv("C:/Users/DELL/Desktop/jupyter projects/practice.csv")
data

   RollNum First Name Last Name   Salary City    Hobby
0      236   rubaisha     munir  1527139  BWP  Singing
1      240    malaika    arshad  2000000  JHL  Dancing
2      251     ayesha    nadeem    98777  SWL  Reading
3      243     fariha     mehdi  1345680  SWL   Baking
4      234     maryam      khan  1457729  KRC  Reading

In [147]:
data["Full Name"]= data["First Name"].str.capitalize() + " " + data["Last Name"].str.capitalize()
data

   RollNum First Name Last Name   Salary City    Hobby       Full Name
0      236   rubaisha     munir  1527139  BWP  Singing  Rubaisha Munir
1      240    malaika    arshad  2000000  JHL  Dancing  Malaika Arshad
2      251     ayesha    nadeem    98777  SWL  Reading   Ayesha Nadeem
3      243     fariha     mehdi  1345680  SWL   Baking    Fariha Mehdi
4      234     maryam      khan  1457729  KRC  Reading     Maryam Khan

# 10) Column Transformation Part2

In [149]:
import pandas as pd
data= pd.read_csv("C:/Users/DELL/Desktop/jupyter projects/practice.csv")
print(data)

   RollNum First Name Last Name   Salary City    Hobby
0      236   rubaisha     munir  1527139  BWP  Singing
1      240    malaika    arshad  2000000  JHL  Dancing
2      251     ayesha    nadeem    98777  SWL  Reading
3      243     fariha     mehdi  1345680  SWL   Baking
4      234     maryam      khan  1457729  KRC  Reading

- **create a new column Bonus that stores 20% of salaries i.e. operation on existing column salary for new column Bonus**

In [151]:
data["Bonus"]= (data["Salary"]/100) * 20
print(data)

   RollNum First Name Last Name   Salary City    Hobby     Bonus
0      236   rubaisha     munir  1527139  BWP  Singing  305427.8
1      240    malaika    arshad  2000000  JHL  Dancing  400000.0
2      251     ayesha    nadeem    98777  SWL  Reading   19755.4
3      243     fariha     mehdi  1345680  SWL   Baking  269136.0
4      234     maryam      khan  1457729  KRC  Reading  291545.8

In [152]:
import pandas as pd
data={"Month":["January", "February","March","April"]}
a= pd.DataFrame(data)
print(a)

      Month
0   January
1  February
2     March
3     April

- **Create a new column through map() that stores first 3 letters of each value in column 'Month'**

In [154]:
def extract(value):
    return value[0:3]
a["Short_Month"]= a["Month"].map(extract)
print(a)

      Month Short_Month
0   January         Jan
1  February         Feb
2     March         Mar
3     April         Apr

# 11)GroupBy:
- The groupby() method allows you to group your data and execute functions on these groups.
- it is used to summarize a large dataset.

In [156]:
import pandas as pd
data= pd.read_excel("C:/Users/DELL/Downloads/ESD.xlsx")
print(data.head(10))

     EEID        Full Name                 Job Title  Department  \
0  E02387      Emily Davis                Sr. Manger          IT
1  E04105    Theodore Dinh       Technical Architect          IT
2  E02572     Luna Sanders                  Director     Finance
3  E02832  Penelope Jordan  Computer Systems Manager          IT
4  E01639        Austin Vo               Sr. Analyst     Finance
5  E00644     Joshua Gupta    Account Representative       Sales
6  E01550      Ruby Barnes                   Manager          IT
7  E04332      Luke Martin                   Analyst     Finance
8  E04533    Easton Bailey                   Manager  Accounting
9  E03838  Madeline Walker               Sr. Analyst     Finance

            Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0  Research & Development  Female      Black   55 2016-04-08         141604
1           Manufacturing    Male      Asian   59 1997-11-29          99975
2     Speciality Products  Female  Caucasian   50 2006-10-26         163099
3           Manufacturing  Female  Caucasian   26 2019-09-27          84913
4           Manufacturing    Male      Asian   55 1995-11-20          95409
5               Corporate    Male      Asian   57 2017-01-24          50994
6               Corporate  Female  Caucasian   27 2020-07-01         119746
7           Manufacturing    Male      Black   25 2020-05-16          41336
8           Manufacturing    Male  Caucasian   29 2019-01-25         113527
9     Speciality Products  Female  Caucasian   34 2018-06-13          77203

   Bonus %        Country       City  Exit Date
0     0.15  United States    Seattle 2021-10-16
1     0.00          China  Chongqing        NaT
2     0.20  United States    Chicago        NaT
3     0.07  United States    Chicago        NaT
4     0.00  United States    Phoenix        NaT
5     0.00          China  Chongqing        NaT
6     0.10  United States    Phoenix        NaT
7     0.00  United States      Miami 2021-05-20
8     0.06  United States     Austin        NaT
9     0.00  United States    Chicago        NaT

**Find Departmentwise Gender count**

In [158]:
gp= data.groupby("Department").agg({"Gender":"count"})
print(gp)

                 Gender
Department
Accounting           96
Engineering         158
Finance             120
Human Resources     125
IT                  241
Marketing           120
Sales               140

**Find the count of Male and Female of each Department using EEID**

In [160]:
gp1= data.groupby(["Department", "Gender"]).agg({"EEID":"count"}) #2 levels of groupby i.e. 1st on department & 2nd on gender basis
print(gp1)

                        EEID
Department      Gender
Accounting      Female    53
                Male      43
Engineering     Female    80
                Male      78
Finance         Female    69
                Male      51
Human Resources Female    64
                Male      61
IT              Female   119
                Male     122
Marketing       Female    57
                Male      63
Sales           Female    76
                Male      64

**Find mean age of each country**

In [162]:
gp2= data.groupby("Country").agg({"Age":"mean"})
print(gp2)

                     Age
Country
Brazil         43.654676
China          45.389908
United States  44.197512

**Find average annual salary of each country**

In [164]:
gp3= data.groupby("Country").agg({"Annual Salary":"mean"})
print(gp3)

               Annual Salary
Country
Brazil         112324.834532
China          113823.532110
United States  113204.794712

**Find maximum annual salary of each country**

In [166]:
gp4= data.groupby("Country").agg({"Annual Salary":"max"})
print(gp4)

               Annual Salary
Country
Brazil                258426
China                 257194
United States         258498

**Find maximum annual salary of each country on the basis of gender**

In [168]:
gp5=data.groupby(["Country","Gender"]).agg({"Annual Salary":"max"})
print(gp5)

                      Annual Salary
Country       Gender
Brazil        Female         258426
              Male           249506
China         Female         249686
              Male           257194
United States Female         258498
              Male           258081

## Conclusion
using groupby we can create summary of data and then perform various operations on that data using agg() to find most accurate and precise results which we cant conclude from entire original dataset

# 12) Merge, Concatenate & Join dataframes
- Merging, joining, and concatenating DataFrames in pandas are important techniques that allow you to combine multiple datasets into one.
- These techniques are essential for cleaning, transforming, and analyzing data.
- Merging, joining, and concatenating are often used interchangeably, but they refer to different methods of combining data.

## i) Merging DataFrames:
- Merging is the process of combining two or more DataFrames into a single DataFrame by linking rows based on one or more common keys.
- The common keys can be one or more columns that have matching values in the DataFrames being merged.
### Different Types of Merges
There are four types of merges in pandas: inner, outer, left, and right.
- **Inner Merge:** Returns only the rows that have matching values in both DataFrames.
- **Outer Merge:** Returns all the rows from both DataFrames and fills in the missing values with NaN where there is no match.
- **Left Merge:** Returns all the rows from the left DataFrame and the matching rows from the right DataFrame. Fills in the missing values with NaN where there is no match.
- **Right Merge:** Returns all the rows from the right DataFrame and the matching rows from the left DataFrame. Fills in the missing values with NaN where there is no match.
#### Examples of How to Perform Different Types of Merges
Let's look at some examples of how to perform different types of merges using Pandas.
- ***Example 1: Inner Merge***

In [172]:
import pandas as pd

df1 = pd.DataFrame({"Key":['A','B','C','D'], "Value":[1,2,3,4]})
print("1st DataFrame:\n ", df1)
df2= pd.DataFrame({"Key":['B','D','E','F'], "Vlaue":[5,6,7,8]})
print("2nd DataFrame:\n ", df2)
#inner merge
inner_merge= pd.merge(df1, df2, on= "Key") #merge is by default set to inner merge
print(inner_merge)

1st DataFrame:
    Key  Value
0   A      1
1   B      2
2   C      3
3   D      4
2nd DataFrame:
    Key  Vlaue
0   B      5
1   D      6
2   E      7
3   F      8
  Key  Value  Vlaue
0   B      2      5
1   D      4      6

- ***Example 2: Outer Merge***

In [174]:
outer_merge=pd.merge(df1,df2, on="Key", how='outer')
print(outer_merge)

  Key  Value  Vlaue
0   A    1.0    NaN
1   B    2.0    5.0
2   C    3.0    NaN
3   D    4.0    6.0
4   E    NaN    7.0
5   F    NaN    8.0

- ***Example 3: Left Merge***

In [176]:
df3 = pd.DataFrame({'Key': ['B', 'D', 'E'], 'value': [5, 6, 7]})
left_merge=pd.merge(df1,df3,on='Key', how='left')
print(left_merge)

  Key  Value  value
0   A      1    NaN
1   B      2    5.0
2   C      3    NaN
3   D      4    6.0

- ***Example 4: Right Merge***

In [178]:
right_merge=pd.merge(df1,df3, on='Key', how='right')
print(right_merge)

  Key  Value  value
0   B    2.0      5
1   D    4.0      6
2   E    NaN      7

## ii)Joining DataFrames
- Joining is a method of combining two DataFrames into one based on their index or column values.
- There are four **types** of joins in pandas: inner, outer, left, and right.
- **Inner Join:** Returns only the rows that have matching index or column values in both DataFrames
- **Outer Join:** Returns all the rows from both DataFrames and fills in the missing values with NaN where there is no match.
- **Left Join:** Returns all the rows from the left DataFrame and the matching rows from the right DataFrame. Fills in the missing values with NaN where there is no match.
- **Right Join:** Returns all the rows from the right DataFrame and the matching rows from the left DataFrame. Fills in the missing values with NaN where there is no match.

- ***Example 1: Inner Join***

In [181]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32]} 
data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'], 
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']} 
df1 = pd.DataFrame(data1,index=['K0', 'K1', 'K2', 'K3'])
df2 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])
print(df1, "\n\n", df2) 
inner_join= df1.join(df2, how='inner')
print(inner_join)

      Name  Age
K0     Jai   27
K1  Princi   24
K2  Gaurav   22
K3    Anuj   32

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons
      Name  Age    Address Qualification
K0     Jai   27  Allahabad           MCA
K2  Gaurav   22    Kannuaj           Phd
K3    Anuj   32  Allahabad          Bcom

- ***Example 2: Outer join***

In [183]:
outer_join=df1.join(df2, how='outer')
print(outer_join)

      Name   Age    Address Qualification
K0     Jai  27.0  Allahabad           MCA
K1  Princi  24.0        NaN           NaN
K2  Gaurav  22.0    Kannuaj           Phd
K3    Anuj  32.0  Allahabad          Bcom
K4     NaN   NaN    Kannuaj        B.hons

- ***Example 3: Left join***

In [185]:
left_join=df1.join(df2, how="left")
print(left_join)

      Name  Age    Address Qualification
K0     Jai   27  Allahabad           MCA
K1  Princi   24        NaN           NaN
K2  Gaurav   22    Kannuaj           Phd
K3    Anuj   32  Allahabad          Bcom

- ***Example 4: Right join***

In [187]:
right_join=df1.join(df2, how="right")
print(right_join)

      Name   Age    Address Qualification
K0     Jai  27.0  Allahabad           MCA
K2  Gaurav  22.0    Kannuaj           Phd
K3    Anuj  32.0  Allahabad          Bcom
K4     NaN   NaN    Kannuaj        B.hons

## iii)Concatenating Dtaframes
- Concatenating is the process of joining two or more DataFrames either vertically or horizontally.
- In pandas, this can be achieved using the concat() function. The concat() function allows you to combine two or more DataFrames into a single DataFrame by stacking them either vertically or horizontally.
- **Examples** of how to concatenate two or more DataFrames using pandas
To concatenate two or more DataFrames ***vertically***, you can use the following code:

In [189]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']})
 
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']})
vertical_concat= pd.concat([df1,df2])
print(vertical_concat)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

- To concatenate two or more DataFrames ***horizontally***, you can use the following code:

In [191]:
horizontal_concat=pd.concat([df1,df2], axis=1)
print(horizontal_concat)

    A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

## Conclusion:
The main difference between join vs merge would be; 
- **join()** is used to combine two DataFrames on the index but not on columns whereas,
- **merge()** is primarily used to specify the columns you want to join on, this also supports joining on indexes and combination of index and columns.
- **concat()** is used for concatenating data frames either vertically or horizontally.

In [193]:
import pandas as pd

# create two dataframes with different shapes and column names
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df2 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 7], 'C': [10, 11, 12]})

print(df1)
print(df2)

# compare dataframes
diff = df1.compare(df2)

# print differences
print(diff)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
   A  B   C
0  1  4  10
1  2  5  11
2  3  7  12
     B          C
  self other self other
0  NaN   NaN    7    10
1  NaN   NaN    8    11
2  6.0   7.0    9    12

# 13)Comparing DataFrames
- The compare method in pandas shows the differences between two DataFrames.
- It compares two data frames, row-wise and column-wise, and presents the differences side by side.
- The compare method can only compare DataFrames of the same shape, with exact dimensions and identical row and column labels.
## Syntax
DataFrame.compare(other, align_axis=1, keep_shape=False, keep_equal=False)
## Parameters
The compare method accepts the following parameters:
- **other:** This is the DataFrame for comparison.
- **align_axis:** This indicates the axis of comparison, with 0 for rows, and 1, the default value, for columns.
- **keep_shape:** This is a boolean parameter. Setting this to True prevents dropping of any row or column, and compare drops rows and columns with all elements same for the two data frames for the default value False.
- **keep_equal:** This is another boolean parameter. Setting this to True shows equal values between the two DataFrames, while compare shows the positions with the same values for the two data frames as NaN for the default value False.

In [195]:
import pandas as pd
print("-----1st DataFrame-----")
df1= pd.DataFrame({'Name':['Ali','Amna','Bisma','Hadi'],'CGPA':[3.51,3.05,2.60,3.00],'Age':[17,18,19,19]})
print(df1)
print("-----2nd DataFrame-----")
df2= pd.DataFrame({'Name':['Ali','Ayesha','Ahmad','Hadi'], 'CGPA':[3.11,3.90,4.00,3.00],'Age':[18,18,20,19]})
print(df2)
comp1= df1.compare(df2)
print("----Comapring 2 DataFrames using only 'other' parameter-----")
print(comp1)
print("-----Comapring 2 DataFrames using 'other' and 'keep_equal' parameter-----")
comp2= df1.compare(df2, keep_equal=True)
print(comp2)
print("-----Comapring 2 DataFrames using 'other' and 'keep_shape' parameter-----")
comp3=df1.compare(df2, keep_shape=True)
print(comp3)
print("-----Comapring 2 DataFrames using 'other', 'keep_equal' and 'keep_shape' parameter-----")
comp4=df1.compare(df2,keep_equal=True, keep_shape=True) #by default align_axis=1
print(comp4)
print("-----Comapring 2 DataFrames using 'other' and 'align_axis' parameter-----")
comp5=df1.compare(df2, align_axis=0)
print(comp5)
print("-----Comapring 2 DataFrames using 'other','keep_equal','keep_shape' and 'align_axis' parameter-----")
comp6=df1.compare(df2, keep_equal=True, keep_shape=True, align_axis=0)
print(comp6)

-----1st DataFrame-----
    Name  CGPA  Age
0    Ali  3.51   17
1   Amna  3.05   18
2  Bisma  2.60   19
3   Hadi  3.00   19
-----2nd DataFrame-----
     Name  CGPA  Age
0     Ali  3.11   18
1  Ayesha  3.90   18
2   Ahmad  4.00   20
3    Hadi  3.00   19
----Comapring 2 DataFrames using only 'other' parameter-----
    Name          CGPA         Age
    self   other  self other  self other
0    NaN     NaN  3.51  3.11  17.0  18.0
1   Amna  Ayesha  3.05  3.90   NaN   NaN
2  Bisma   Ahmad  2.60  4.00  19.0  20.0
-----Comapring 2 DataFrames using 'other' and 'keep_equal' parameter-----
    Name          CGPA        Age
    self   other  self other self other
0    Ali     Ali  3.51  3.11   17    18
1   Amna  Ayesha  3.05  3.90   18    18
2  Bisma   Ahmad  2.60  4.00   19    20
-----Comapring 2 DataFrames using 'other' and 'keep_shape' parameter-----
    Name          CGPA         Age
    self   other  self other  self other
0    NaN     NaN  3.51  3.11  17.0  18.0
1   Amna  Ayesha  3.05  3.90   NaN   NaN
2  Bisma   Ahmad  2.60  4.00  19.0  20.0
3    NaN     NaN   NaN   NaN   NaN   NaN
-----Comapring 2 DataFrames using 'other', 'keep_equal' and 'keep_shape' parameter-----
    Name          CGPA        Age
    self   other  self other self other
0    Ali     Ali  3.51  3.11   17    18
1   Amna  Ayesha  3.05  3.90   18    18
2  Bisma   Ahmad  2.60  4.00   19    20
3   Hadi    Hadi  3.00  3.00   19    19
-----Comapring 2 DataFrames using 'other' and 'align_axis' parameter-----
           Name  CGPA   Age
0 self      NaN  3.51  17.0
  other     NaN  3.11  18.0
1 self     Amna  3.05   NaN
  other  Ayesha  3.90   NaN
2 self    Bisma  2.60  19.0
  other   Ahmad  4.00  20.0
-----Comapring 2 DataFrames using 'other','keep_equal','keep_shape' and 'align_axis' parameter-----
           Name  CGPA  Age
0 self      Ali  3.51   17
  other     Ali  3.11   18
1 self     Amna  3.05   18
  other  Ayesha  3.90   18
2 self    Bisma  2.60   19
  other   Ahmad  4.00   20
3 self     Hadi  3.00   19
  other    Hadi  3.00   19

## Conclusion
we use .compare() to find the difference between 2 dataframes by comparing them. For example, 1st dataframe is of year 2022 and other one is of 2023 we want to compare them to see differences made in one year

# 14) Pivoting & Melting DataFrames
## i) Pivoting
### ***Pandas.pivot()***
- pivot() allows you to transform or reshape data
- pandas.pivot(index, columns, values) function produces a pivot table based on 3 columns of the DataFrame.Uses unique values from the index/columns and fills them with values.
- **Syntax:** pandas.pivot(index, columns, values)
- **Parameters:**

**index[ndarray] :** Labels to use to make new frame’s index

**columns[ndarray] :** Labels to use to make new frame’s columns

**values[ndarray] :** Values to use for populating new frame’s values

- **Returns:** Reshaped DataFrame
- **Exception:** ValueError raised if there are any duplicates.
#### Creating a Sample DataFrame:

In [198]:
import pandas as pd
df= pd.DataFrame({"Rollnum":[229,236,240,243,251],"Name":["Malaika Mehmood", "Rubaisha Munir", "Malaika Arshad", "Fariha Mehdi","Ayesha Nadeem"],"CGPA":[3.5,3.5,3.7,3.1,3.2],"Age":[21,20,21,22,21]})
print(df)

   Rollnum             Name  CGPA  Age
0      229  Malaika Mehmood   3.5   21
1      236   Rubaisha Munir   3.5   20
2      240   Malaika Arshad   3.7   21
3      243     Fariha Mehdi   3.1   22
4      251    Ayesha Nadeem   3.2   21

#### Pandas pivot() Function Examples
Below are some examples by which we can pivot a DataFrame using Pandas pivot() function in Python:
- **Creating and Pivot a DataFrame:**

In [200]:
print("taking only cgpa as value")
p2= df.pivot(index='Rollnum',columns='Name', values='CGPA')
print(p2)
print("taking only age as value")
p3=df.pivot(index="Rollnum",columns="Name",values="Age")
print(p3)

taking only cgpa as value
Name     Ayesha Nadeem  Fariha Mehdi  Malaika Arshad  Malaika Mehmood  \
Rollnum
229                NaN           NaN             NaN              3.5
236                NaN           NaN             NaN              NaN
240                NaN           NaN             3.7              NaN
243                NaN           3.1             NaN              NaN
251                3.2           NaN             NaN              NaN

Name     Rubaisha Munir
Rollnum
229                 NaN
236                 3.5
240                 NaN
243                 NaN
251                 NaN
taking only age as value
Name     Ayesha Nadeem  Fariha Mehdi  Malaika Arshad  Malaika Mehmood  \
Rollnum
229                NaN           NaN             NaN             21.0
236                NaN           NaN             NaN              NaN
240                NaN           NaN            21.0              NaN
243                NaN          22.0             NaN              NaN
251               21.0           NaN             NaN              NaN

Name     Rubaisha Munir
Rollnum
229                 NaN
236                20.0
240                 NaN
243                 NaN
251                 NaN

- **Creating a Multi-level Pivot Table with Pandas DataFrame**

In [202]:
p1= df.pivot(index="Rollnum",columns="Name")
print(p1)
#it can also be done as
print("ANOTHER WAY")
p4= df.pivot(index="Rollnum", columns="Name", values=["Age","CGPA"])
print(p4)

                 CGPA                                              \
Name    Ayesha Nadeem Fariha Mehdi Malaika Arshad Malaika Mehmood
Rollnum
229               NaN          NaN            NaN             3.5
236               NaN          NaN            NaN             NaN
240               NaN          NaN            3.7             NaN
243               NaN          3.1            NaN             NaN
251               3.2          NaN            NaN             NaN

                                 Age                              \
Name    Rubaisha Munir Ayesha Nadeem Fariha Mehdi Malaika Arshad
Rollnum
229                NaN           NaN          NaN            NaN
236                3.5           NaN          NaN            NaN
240                NaN           NaN          NaN           21.0
243                NaN           NaN         22.0            NaN
251                NaN          21.0          NaN            NaN


Name    Malaika Mehmood Rubaisha Munir
Rollnum
229                21.0            NaN
236                 NaN           20.0
240                 NaN            NaN
243                 NaN            NaN
251                 NaN            NaN
ANOTHER WAY
                  Age                                              \
Name    Ayesha Nadeem Fariha Mehdi Malaika Arshad Malaika Mehmood
Rollnum
229               NaN          NaN            NaN            21.0
236               NaN          NaN            NaN             NaN
240               NaN          NaN           21.0             NaN
243               NaN         22.0            NaN             NaN
251              21.0          NaN            NaN             NaN

                                CGPA                              \
Name    Rubaisha Munir Ayesha Nadeem Fariha Mehdi Malaika Arshad
Rollnum
229                NaN           NaN          NaN            NaN
236               20.0           NaN          NaN            NaN
240                NaN           NaN          NaN            3.7
243                NaN           NaN          3.1            NaN
251                NaN           3.2          NaN            NaN


Name    Malaika Mehmood Rubaisha Munir
Rollnum
229                 3.5            NaN
236                 NaN            3.5
240                 NaN            NaN
243                 NaN            NaN
251                 NaN            NaN

- **ValueError Raised in Pivoting a DataFrame**
  
Raise ValueError when there are any index, columns combinations with multiple values.

In [204]:
import pandas as pd
df= pd.DataFrame({"Rollnum":[229,229,240,243,251],"Name":["Malaika Mehmood", "Malaika Mehmood", "Malaika Arshad", "Fariha Mehdi","Ayesha Nadeem"],"CGPA":[3.5,3.5,3.7,3.1,3.2],"Age":[21,20,21,22,21]})
print(df)

   Rollnum             Name  CGPA  Age
0      229  Malaika Mehmood   3.5   21
1      229  Malaika Mehmood   3.5   20
2      240   Malaika Arshad   3.7   21
3      243     Fariha Mehdi   3.1   22
4      251    Ayesha Nadeem   3.2   21

In [205]:
#p5= df.pivot(index="Rollnum",columns="Name",values="Age")
#print(p5)

### ***Pandas.pivot_table()***
- Pivot table is used to summarize and aggregate data inside dataframe
- create a spreadsheet-style pivot table as a DataFrame.
- Levels in the pivot table will be stored in MultiIndex objects (hierarchical indexes) on the index and columns of the result DataFrame.
- **Syntax:** pandas.pivot_table(data, values=None, index=None, columns=None, aggfunc=’mean’, fill_value=None, margins=False, dropna=True, margins_name=’All’)
- **Parameters:**

**data :** DataFrame

**values :** column to aggregate, optional

**index:** column, Grouper, array, or list of the previous

**columns:** column, Grouper, array, or list of the previous

**aggfunc:** function, list of functions, dict, default numpy.mean

**->** If list of functions passed, the resulting pivot table will have hierarchical columns whose top level are the function names.

**->** If dict is passed, the key is column to aggregate and value is function or list of functions

**fill_value[scalar, default None] :** Value to replace missing values with

**margins[boolean, default False] :** Add all row / columns (e.g. for subtotal / grand totals)

**dropna[boolean, default True] :** Do not include columns whose entries are all NaN

**margins_name[string, default ‘All’] :** Name of the row / column that will contain the totals when margins is True.


- **Returns:** DataFrame

- **Create a simple dataframe**

In [208]:
import pandas as pd
df= pd.read_csv("C:/Users/DELL/Downloads/weather2.csv")
print(df)

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

- **Simple Pivot table**

In [210]:
print("1st pivot table without passing aggfunc which by default is set to 'mean' ")
pt1= pd.pivot_table(df, index="city", columns="date", values=["temperature", "humidity"])
print(pt1)

1st pivot table without passing aggfunc which by default is set to 'mean'
         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai       81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

- **Using aggregate function**

In [212]:
print("2nd pivot table using aggfunc ")
pt2= pd.pivot_table(df, index="city", columns="date", aggfunc= "mean") #try using diff, count, sum etc.
print(pt2)

2nd pivot table using aggfunc
         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai       81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

- **by default margins=False changing it to True**
- will add 'All' in row and also in column showing the average of the two values columnwise and rowwise

In [214]:
print("3rd pivot table using margins which by default is set to false")
pt3= pd.pivot_table(df, index='city', columns='date', aggfunc='mean', margins=True)
print(pt3)

3rd pivot table using margins which by default is set to false
         humidity                 temperature
date     5/1/2017 5/2/2017    All    5/1/2017 5/2/2017     All
city
mumbai      81.50    55.50  68.50       76.50     81.0  78.750
new york    55.00    61.00  58.00       63.00     71.0  67.000
All         68.25    58.25  63.25       69.75     76.0  72.875

#### **Grouper() in pivot table**
A Grouper allows the user to specify a groupby instruction for a target object

In [216]:
#creating dataframe
import pandas as pd
df= pd.read_csv("C:/Users/DELL/Downloads/weather3.csv")
print(df)

        date      city  temperature  humidity
0   5/1/2017  new york           65        56
1   5/2/2017  new york           61        54
2   5/3/2017  new york           70        60
3  12/1/2017  new york           30        50
4  12/2/2017  new york           28        52
5  12/3/2017  new york           25        51

**find average temperature of new york in month of may and average temperature in month of december. this is somethiong that you can do by using pure table grouper**

In [218]:
print("first converting the type of 'date' column from string to DateTime otherwise we will get error using grouper")
df['date']=pd.to_datetime(df['date'])
print(df)

first converting the type of 'date' column from string to DateTime otherwise we will get error using grouper
        date      city  temperature  humidity
0 2017-05-01  new york           65        56
1 2017-05-02  new york           61        54
2 2017-05-03  new york           70        60
3 2017-12-01  new york           30        50
4 2017-12-02  new york           28        52
5 2017-12-03  new york           25        51

In [219]:
pt4= pd.pivot_table(df, index=pd.Grouper(freq='ME', key='date'), columns="city") #'ME' for month
print(pt4)

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667

## ii)Pandas.melt
This function is useful to massage a DataFrame into a format where one or more columns are identifier variables (id_vars), while all other columns, considered measured variables (value_vars), are “unpivoted” to the row axis, leaving just two non-identifier columns, ‘variable’ and ‘value’.

**Creating a sample dataframe:**

In [222]:
import pandas as pd
df= pd.DataFrame({"Rollnum":[229,236,240,243,251],"Name":["Malaika Mehmood", "Rubaisha Munir", "Malaika Arshad", "Fariha Mehdi","Ayesha Nadeem"],"CGPA":[3.5,3.5,3.7,3.1,3.2],"Age":[21,20,21,22,21]})
print(df)

   Rollnum             Name  CGPA  Age
0      229  Malaika Mehmood   3.5   21
1      236   Rubaisha Munir   3.5   20
2      240   Malaika Arshad   3.7   21
3      243     Fariha Mehdi   3.1   22
4      251    Ayesha Nadeem   3.2   21

In [223]:
print("display only names")
m1= pd.melt(df, id_vars=["Rollnum"], value_vars=["Name"])
print(m1)
print("display cgpa and age as variable and value")
m2= pd.melt(df, id_vars=["Rollnum"], value_vars=["CGPA", "Age"])
print(m2)

display only names
   Rollnum variable            value
0      229     Name  Malaika Mehmood
1      236     Name   Rubaisha Munir
2      240     Name   Malaika Arshad
3      243     Name     Fariha Mehdi
4      251     Name    Ayesha Nadeem
display cgpa and age as variable and value
   Rollnum variable  value
0      229     CGPA    3.5
1      236     CGPA    3.5
2      240     CGPA    3.7
3      243     CGPA    3.1
4      251     CGPA    3.2
5      229      Age   21.0
6      236      Age   20.0
7      240      Age   21.0
8      243      Age   22.0
9      251      Age   21.0

- **You can also set the name of the variable and value attributes**

In [225]:
print("setting the name of variable and value\n\n")
m3= pd.melt(df, id_vars=["Rollnum"], value_vars=["Name", "Age"], var_name="attributes", value_name="details")
print(m3)

setting the name of variable and value


   Rollnum attributes          details
0      229       Name  Malaika Mehmood
1      236       Name   Rubaisha Munir
2      240       Name   Malaika Arshad
3      243       Name     Fariha Mehdi
4      251       Name    Ayesha Nadeem
5      229        Age               21
6      236        Age               20
7      240        Age               21
8      243        Age               22
9      251        Age               21